### ISSUE TITLE
Screenshots look squashed in Instance Manager

### ISSUE THREAD

**Issue by ghost** [killpowa/Twickt-Launcher#1073]
**Describe the bug**

**To Reproduce**
1. Go to the Instance Manager for any instance with screenshots.
2. Click on 'screenshots'.
3. All images appear squashed.

**Expected behavior**
Screenshots are centered.

**Possible solutions**
Removed for being redundant

**Screenshots**
![image](https://user-images.githubusercontent.com/82655227/133926971-428edbb3-e9cb-402a-8992-212bc5bcbafc.png)

**Operating System:**
- OS: Windows
- Version: 10 Home Edition (20H2)
- Java Version: 8
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
The suggested fix needs to be merged with the existing CSS.

**Comment by Ladvace** [comment]
I just made PR for that: https://github.com/gorilla-devs/GDLauncher/pull/1074

**Comment by ghost** [comment]
Nice, much less hacky
