### ISSUE TITLE
Failing to Build Git Beta 1.1.15

### ISSUE THREAD

**Issue by SaltSouls** [killpowa/Twickt-Launcher#1081]
**Describe the bug**
The beta version of GDLauncher is failing to build when using either rua, or paru.
```
==> Starting prepare()...
patching file src/app/desktop/utils/index.js
Hunk #2 FAILED at 312.
1 out of 2 hunks FAILED -- saving rejects to file src/app/desktop/utils/index.js.rej
patching file src/common/reducers/actions.js
Hunk #1 FAILED at 83.
Hunk #2 succeeded at 1194 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file src/common/reducers/actions.js.rej
patching file src/common/modals/InstanceExport/CurseForge/ThirdStep.js
patching file public/electron.js
Hunk #2 FAILED at 198.
Hunk #3 succeeded at 632 (offset 16 lines).
1 out of 3 hunks FAILED -- saving rejects to file public/electron.js.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
Build failed with exit code 4 in /home/gigapain/.cache/rua/build/gdlauncher-git
```

**To Reproduce**
1. Run `rua install gdlauncher-git`
2. Build package

**Expected behavior**
Should build.

**Operating System:**
- OS: Manjaro Linux x86_64
- Version: 5.14.7-2
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A

**Comment by huantianad** [comment]
This is an issue with the AUR package, not the upstream program. Please report this to the AUR package.

**Comment by Eskaan** [comment]
I would recommend you to use our default build and development process via git and npm.

**Comment by huantianad** [comment]
@Code-Ac The AUR package essentially does the same thing, just applies some patches before hand, which change the 7z path. Since there were edits to the 7z code, the patch needs to be edited as well. I have my own version of the patch [here](https://aur.archlinux.org/cgit/aur.git/tree/use-system-7za-and-disable-updater.patch?h=gdlauncher-beta) which should work.

**Comment by Eskaan** [comment]
Ah okay 😅
