### ISSUE TITLE
really low fps

### ISSUE THREAD

**Issue by DragonSnail9888** [killpowa/Twickt-Launcher#1088]
I just switched  to GDlauncher and really like it, but when I launched it for the first time, I got really low fps. I have a ryzen 7 and 2070 super so that cant be the problem. Im using win 10 and usually get 300 Fps vanilla. I tried Fabulously Optimized pack on the normal launcher and got over 500 fps. With the gdlauncher only 100. I cant find the problem. Can somebody help?

**Comment by Eskaan** [comment]
Probably you need to increase your RAM for the JRE (Settings/Java/Memory)
Adding custom args can also bring good performance but needs the knowledge how to do it

**Comment by DragonSnail9888** [comment]
Thanks for te quick replay. OK, I did, and it worked, but I think the main problem was VSync, which I didnt see in the sodium options until now, when I disabled it, I went from 60 to 450 fps.

**Comment by Eskaan** [comment]
Oh cool. Can you close this?
