### ISSUE TITLE
When trying to install 1.17.1 instance it gets stuck at Downloading forge installer 0%

### ISSUE THREAD

**Issue by NimbusFox** [killpowa/Twickt-Launcher#1093]
**Describe the bug**
When trying to install 1.17.1 instance it gets stuck at Downloading forge installer 0%

**To Reproduce**
1. Create a forge instance for 1.17.1
2. Wait for it to download game files
3. Wait for it to download forge
4. It hangs on 0%

**Expected behavior**
It installs forge without issue

**Possible solutions**
I have tried downloading the installer manually but it says the hash is mismatched

**Screenshots**
https://i.imgur.com/wDBP0wN.png
https://i.imgur.com/VG9I1hH.png

**Operating System:**
- OS: Linux
- Version: 5.14.7-2-MANJARO
- Java Version: 8
- Minecraft Version: 1.17.1
- Mod Loader: Forge

**Comment by floriaaan** [comment]
Same here, it seems that certificate has expired (open DevTools shows that)

**Comment by Eskaan** [comment]
Duplicate of #1086
