### ISSUE TITLE
Modpack download hangs at 0%

### ISSUE THREAD

**Issue by BettaGeorge** [killpowa/Twickt-Launcher#1096]
**Description**
When downloading a curseforge modpack, the launcher installs the game files, then hangs on 0% of "downloading forge installer" forever.
This is the 1.15 beta because the stable version does not work on arch at all (but there is already a ticket for that).

**Reproducing**
Install gd-launcher-beta (1.15) on Manjaro.
Add a new instance. Try to download a curseforge modpack.

**System specs**
OS: Manjaro 21.1.4

**Comment by Eskaan** [comment]
Duplicate of #1086
