### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by johannesmateboer** [killpowa/Twickt-Launcher#1099]
**Describe the bug**
When I try to import an instance by url, an error appears in the console saying the certificate has expired

```
Import.js:62 Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497)
    at TLSSocket.emit (events.js:315)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)
```

**To Reproduce**
1. Create zip and put online (on a valid, checked location)
2. Import instance by url.

**Expected behavior**
The instance should just import (as it once did!)

**Possible solutions**
It looks like a certificate-error, not sure which one, but it's expired. And yes, I did check my side. Several different platforms and locations give the same error.

**Operating System:**
- OS: Win10
- Java Version: N/A
- Minecraft Version: 1.16.5
- Mod Loader: Fabric

**Comment by huantianad** [comment]
Duplicate of #1086

**Comment by johannesmateboer** [comment]
The new beta works. So it seems to be a duplicate indeed.

**Comment by Eskaan** [comment]
Please close your issues after they have been resolved.
