### ISSUE TITLE
Download Modrinth Mod

### ISSUE THREAD

**Issue by MG8853** [killpowa/Twickt-Launcher#1111]
**Is your feature request related to a problem? Please describe.**
I want to download modrinth mods with GD Launcher!

**Describe the solution you'd like**
I want you to be able to download mods from Modrinth

**Additional context**
https://modrinth.com/
https://github.com/modrinth/labrinth

**Comment by Eskaan** [comment]
We’ve already took long discussions about modrinth in another issue, and (from my knowledge) we are currently waiting for the v2 of their API :)

**Comment by Eskaan** [comment]
Duplicate of #768
