### ISSUE TITLE
Discord link in application is invalid

### ISSUE THREAD

**Issue by jpwanabe** [killpowa/Twickt-Launcher#1112]
**Describe the bug**
The discord link in the application settings is an invalid link

**To Reproduce**
1. Go to settings
2. Click on the discord icon
3. ???

**Expected behavior**
Invited to discord
**Possible solutions**
Some ideas of how you would solve this issue, if possible
Update link for next update
**Screenshots**
https://i.imgur.com/Z7P4u2g.png
https://i.imgur.com/I3kkpOI.png
**Operating System:**
- OS:Windows
- Version: 10

**Additional context**

**Comment by huantianad** [comment]
This seems to be fixed in the latest beta,

**Comment by huantianad** [comment]
@Code-Ac can you close this issue?

**Comment by Eskaan** [comment]
@huantianad here you go

**Comment by Eskaan** [comment]
Just ping me on dc/gh and I will be there :)
