### ISSUE TITLE
Instance installation stalls at forge installer...

### ISSUE THREAD

**Issue by postal291** [killpowa/Twickt-Launcher#1113]
**Describe the bug**
While attempting to install a new instance of a curseforge modpack, the installation stops at "Downloading forge installer..." and sits at 0% indefinitely.

**To Reproduce**
1. Click the [+] to add a new instance.
2. Click on CurseForge tab.
3. Select Download latest for ANY modpack
4. Name the instance and Click 'Next'.

**Expected behavior**
Expect the installation to download modpack, obtain mod files, download / install forge, extract remaining modpack files and complete the installation.

**Operating System:**
- OS: Windows 10
- Java Version: both 8 and 16 are installed, launcher autodetect utilized.
- Minecraft Version: (doesn't seem relevant) but tested against 1.10.2, 1.12.2 and 1.17
- Mod Loader: (doesn't seem relevant) but tested against both forge and fabric.

Attempted the following:
- Retry installation of modpack
- Tried another modpack (several)
- Relaunch launcher
- Reinstall launcher
- Reinstall java 8
- Reinstall java 16

**Comment by huantianad** [comment]
Duplicate of #1086

**Comment by postal291** [comment]
@huantianad Thanks, never saw that in my searches initially.  The Beta has fixed the issue :)
