### ISSUE TITLE
Any way to recover instance

### ISSUE THREAD

**Issue by CaptainBignose** [killpowa/Twickt-Launcher#1114]
I was having issues with the forge downloader stuck at 0%, then I changed to the beta release launcher which seemed to fix the issue. However in trying to mess with settings and such, I must have duplicated an instance I had. I deleted the duplicate, but then when I loaded the original all the mods were gone and my saves missing. Is there any way to recover this data or is it lost forever?

**Comment by Eskaan** [comment]
From my knowledge, deleting is deleting. You could try to go into your instance folder and look if it’s still there (and corrupted) but this would enable you to fix it.

**Comment by CaptainBignose** [comment]
Okay, just wanted to see if there was any folder for deleted instances of history somewhere. I will be more careful in the future and backup my worlds. Thanks!
