### ISSUE TITLE
Error while downloading/Extremely slow download

### ISSUE THREAD

**Issue by urioTV** [killpowa/Twickt-Launcher#1115]
**Describe the bug**
When i try to download it's really slow(i mean really slow after an hour it's 10%) and logs are full of errors. I tried stable and beta without luck. It's fresh install of GDLauncher on this PC.

**To Reproduce**
1. Run GD Launcher
2. Create new instance and start downloading
3. Download is really slow and in devtools you can see errors

**Screenshots**
![Dvt2cmjQ3H](https://user-images.githubusercontent.com/45111726/137541778-f535c954-65d5-4f28-8271-3caccf145aa5.png)

The last error is repeating constantly.

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8/16
- Minecraft Version: 1.17.1, 1.17, 1.16.5(and probably all others)
- Mod Loader: Doesn't matter

**Comment by conrad-mo** [comment]
I have the same issue as well

**Comment by Destrolaric** [comment]
+ Same problem, something was broken

**Comment by conrad-mo** [comment]
I fixed it by switching to the beta

**Comment by urioTV** [comment]
> I fixed it by switching to the beta

For me switching doesn't work.

**Comment by conrad-mo** [comment]
> 
> 
> > I fixed it by switching to the beta
> 
> For me switching doesn't work.

Check if you are actually on the beta by the bottom of the settings page.

**Comment by urioTV** [comment]
> > > I fixed it by switching to the beta
> > 
> > 
> > For me switching doesn't work.
> 
> Check if you are actually on the beta by the bottom of the settings page.

![image](https://user-images.githubusercontent.com/45111726/137635737-ce53c35c-da38-4764-ae98-fde7fdb4d030.png)

**Comment by mrsaminus** [comment]
i have the same issue, and on beta branch

**Comment by hyperfrost12** [comment]
i am having the same issue but on windows 11

**Comment by hyperfrost12** [comment]
i am having the same issue.

**Comment by torbenbn** [comment]
I am also seeing this behavior on Windows 10 with a fresh install of GD Launcher v1.1.29 (as of 2023-01-22):
![image](https://user-images.githubusercontent.com/3580244/213894288-04bff09e-79fb-4409-b6d9-77931e5668c6.png)
Very slow progress in the main window and endless errors in the console window.
I see this behavior for both modded and vanilla.

**Comment by torbenbn** [comment]
FWIIW, I just tried the current beta: 1.1.30 beta.1and here I don't get the endless errors and the download goes much smoother.
I did see these two errors in the console right when the download started, but nothing after that:
![image](https://user-images.githubusercontent.com/3580244/213894651-8b2705c1-5478-40ad-a349-ae15701231d1.png)

**Comment by Eskaan** [comment]
Duplicate of #1513
