### ISSUE TITLE
Cannot log into minecraft with microsoft account "Error: Error occured while fetching token from Xbox Secure Token Service."

### ISSUE THREAD

**Issue by wr7** [killpowa/Twickt-Launcher#1116]
I'm able to login to my minecraft account in the official minecraft launcher, but whenever I use the same credentials on the GDLauncher launcher, it gives me this error. I'm running the linux version (specifically the appimage version v1.1.14). These are all of the errors that I get when I launch GDLauncher and try to sign in: 
![image](https://user-images.githubusercontent.com/53203261/137591635-b348a8e1-74ff-4037-af03-76dd25e4ed54.png)

**Comment by furtabs** [comment]
Your underage. Change the DOB to 18 or older

**Comment by Eskaan** [comment]
Duplicate of #1116

**Comment by Eskaan** [comment]
oh f. Wrong issue

**Comment by wr7** [comment]
i had to wait a bit after changing the DOB of my Microsoft account, but it works now

**Comment by Jugwasntavailable** [comment]
I have the same issue. Even though my Microsoft account is above 18.
