### ISSUE TITLE
npm i Problems

### ISSUE THREAD

**Issue by NolvusMadeIt** [killpowa/Twickt-Launcher#1119]
So... No matter what versions node I install, apparently installing the dependencies is giving me a stoke and a heart attack at the same time.

Even when prompt to fix and address the issues its having via: `npm audit fix --force`, we go back to the same issues. I also made sure that all requirements was installed and updated including rust. And before someone ask me if I am using Win11, the answers hell no as that isnt even stable yet for release.

Anyone find a work around or temp/perma fix? If so, I could use some type of hope! <3

**Comment by Eskaan** [comment]
You mean the audit log issues? They are not caused by us, and we cant really do much except of creating prs on the repos to fix them. I just ignore them because its normal for node packages to have vulnerabilities.

**Comment by NolvusMadeIt** [comment]
Ok, then how do I get it to work if I cant use `npm run dev`, or even `npm audit fix` to fix the issues so it will work? This is coming straight off the repo and fresh. Help me to understand on what to do.

**Comment by NolvusMadeIt** [comment]
I believe I got it to work again but deleting all NodeJS installations including the cache folder. I then reinstalled with the latest NodeJS LTS.

It also has the choco option which I did not take and installed it manually myself directly from the choc site itself.

Ran npm install again, then a couple of audit fixes and 1 --force then ran the app and it all was working like normal again.

However, I still get this error:
`npm run dev

> gdlauncher@1.1.15-beta.5 dev C:\Users\nanob\Projects\WGLauncher
> npm run build-electron:dev && cross-env-shell NODE_ENV=development APP_TYPE=electron BROWSER=none "npm run start-electron"


> gdlauncher@1.1.15-beta.5 build-electron:dev C:\Users\nanob\Projects\WGLauncher
> cross-env-shell NODE_ENV=development REACT_APP_RELEASE_TYPE=setup webpack --config ./scripts/electronWebpackConfig.js --color

[webpack-cli] Failed to load 'C:\Users\nanob\Projects\WGLauncher\scripts\electronWebpackConfig.js' config
[webpack-cli] TypeError: webpack.NamedModulesPlugin is not a constructor
    at Object.<anonymous> (C:\Users\nanob\Projects\WGLauncher\scripts\electronWebpackConfig.js:71:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at WebpackCLI.tryRequireThenImport (C:\Users\nanob\Projects\WGLauncher\node_modules\webpack-cli\lib\webpack-cli.js:244:16)
    at loadConfigByPath (C:\Users\nanob\Projects\WGLauncher\node_modules\webpack-cli\lib\webpack-cli.js:1710:30)
    at C:\Users\nanob\Projects\WGLauncher\node_modules\webpack-cli\lib\webpack-cli.js:1765:11
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gdlauncher@1.1.15-beta.5 build-electron:dev: `cross-env-shell NODE_ENV=development REACT_APP_RELEASE_TYPE=setup webpack --config ./scripts/electronWebpackConfig.js --color`      
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gdlauncher@1.1.15-beta.5 build-electron:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nanob\AppData\Roaming\npm-cache\_logs\2021-10-19T01_25_52_554Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gdlauncher@1.1.15-beta.5 dev: `npm run build-electron:dev && cross-env-shell NODE_ENV=development APP_TYPE=electron BROWSER=none "npm run start-electron"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gdlauncher@1.1.15-beta.5 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nanob\AppData\Roaming\npm-cache\_logs\2021-10-19T01_25_52_584Z-debug.log`

**Comment by Eskaan** [comment]
Are you even Talking about the Project you’re creating an issue on??
Your npm log shows me something else, it tells that you’re trying npm i in your fork of the project. We are not responsible for changes you made to the package.json file in your project.
