### ISSUE TITLE
Forge stuck downloading

### ISSUE THREAD

**Issue by suited-1** [killpowa/Twickt-Launcher#1121]
**Describe the bug**
Same issue as #998 #1008 forge is stuck at either 99% 0% or 100%. 
 
**To Reproduce**
attempt to make a 1.17.1 forge instance with any forge version

**Expected behavior**
The instance to be successfully created

**Possible solutions**
N/A

**Screenshots**

**Operating System:**
- OS: Pop!OS
- Version: 
- Java Version: [16]
- Minecraft Version: [1.17.1]
- Mod Loader: [e.g. Forge]

**Additional context**
GDlauncher version is 1.1.14, other issue trackers said it was fixed in version 1.1.12

**Comment by Sixdd6** [comment]
Same issue here, any Forge for 1.17.1 refuses to download properly and stays stuck at 0%:

OS: Windows 11
Java: 11, 14, 16
GDLauncher: 1.1.14

**Comment by Eskaan** [comment]
Duplicate of #1086
