### ISSUE TITLE
[BUG?] Certificate expired

### ISSUE THREAD

**Issue by hron84** [killpowa/Twickt-Launcher#1142]
**Describe the bug**
I honestly do not know where you download Forge Installer, but the site's certificate is expired. But the issue is not only the expired certificate. When the launcher fails to download the installer, the progress bar is stuck at "Downloading forge installer... 0%". 

I have two things to ask:

 - Could you please take a look at this expired certificate? 
 - Could you please add a correct exception handling for Forge installation and pop up an error message on GUI to avoid digging around in the developer terminal?

**To Reproduce**
1. Try to install a Vanilla / Forge 1.12 modpack

**Expected behavior**
A normal installation progress

**Ideas how to solve this problem**

Maybe you should cache the already downloaded Forge installers somewhere on the FS

**Operating System:**
- OS: Linux
- Version: 1.1.14
- Java Version: N/A
- Minecraft Version: 1.12.2
- Mod Loader: Forge 14.23.5.2854 / 14.23.5.2855

**Additional context**

```
asyncToGenerator.js:6 Uncaught (in promise) Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497)
    at TLSSocket.emit (events.js:315)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)
```

**Comment by Eskaan** [comment]
Duplicate of #1086

**Comment by Eskaan** [comment]
You will have to upgrade to the latest Beta version, it’s fixed there. (Further information in the linked issue)
