### ISSUE TITLE
Can't Update OceanBlock Modpack to any Version other than the original I downloaded

### ISSUE THREAD

**Issue by Parkyy03** [killpowa/Twickt-Launcher#1144]
**Describe the bug**
When I go to update OceanBlock to any version other than the original version I first downloaded, it shows the version is downloading but when it's completed the version of the modpack has no changes but it's still labelled as the newest version of the pack.

**To Reproduce**
1. Go to update OceanBlock from any version other than the original version you downloaded
2. Wait for the download to be fully completed
3. Check the files to see if the changes that are stated have been applied
4. See that the files are in the same state as they were before the update.

**Expected behavior**
I would expect the modpack to download the new versions of the mods and any new mods that have been added or taken out of the pack.

**Possible solutions**
Looking over the console and source code to see if any errors come up when installing the pack that may not be stated on the actual client. Checking for any communication errors with the FTB app.

**Screenshots**
N/A

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: both 8 and 16
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
N/A

**Comment by Eskaan** [comment]
Any errors in the console while updating?
On which launcher version are you? (Settings at the bottom)

**Comment by Parkyy03** [comment]
Only errors I had was these:
![error](https://user-images.githubusercontent.com/50531851/140027492-bae38eb9-e2eb-4d04-ac6f-9c08b89bda32.JPG)

And the current version I'm on is: v1.1.15-beta.6

**Comment by Parkyy03** [comment]
Also attempted to update other modpacks and it seems to work on every modpack other than packs from the FTB App

**Comment by Knoxxar** [comment]
Looks like an Cert Error, i have  the same Problem. Tried to Update Ragnamod VI and install a new pack.

Launcher Version:  1.1.14

![Error](https://user-images.githubusercontent.com/28510961/140093375-58622aa3-fa39-4926-a5ee-6c979ab2c5c0.PNG)

**Comment by Parkyy03** [comment]
> Looks like an Cert Error, i have the same Problem. Tried to Update Ragnamod VI and install a new pack.
> 
> Launcher Version: 1.1.14
> 
> ![Error](https://user-images.githubusercontent.com/28510961/140093375-58622aa3-fa39-4926-a5ee-6c979ab2c5c0.PNG)

The error with downloading a new pack is with the version of GDlauncher you have, if you download the latest beta version it fixes that problem.

**Comment by Parkyy03** [comment]
After release 1.1.15 the FTB downloads still aren't working, at least for me they're not.

**Comment by gusaln** [comment]
On Version 1.1.15 -> When you press the FTB tab on the "Add New Instance" modal this is the response on the network tab of the debug console:
![gdlauncher_ftb_packs_bug](https://user-images.githubusercontent.com/7484242/141646157-66a1d3b9-b933-4449-8700-a0073a14035a.png)

**Comment by lord-ne** [comment]
Still getting this issue in version 1.1.23 (specifically, for the Direwolf20 1.18 pack). I can install the latest version, but I can't update my existing instance to the latest version

**Comment by Eskaan** [comment]
Yeah the old CurseForge API recently got shut down, so only v1.1.23 works now.
@lord-ne I expect you to have another issue here, I guess some mod authors have disabled theirs party programs on their mods. see #1342  for more info.
