### ISSUE TITLE
Downloading forge installer never end on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by Lyght28** [killpowa/Twickt-Launcher#1145]
**Describe the bug**
The _downloading forge installer_ never stop. 

**To Reproduce**
1. Try to create a new forge modded instance (from curse, ftb or zip).
2. Wait for the _download game files_ to end.
3. The _downloading forge installer_ stay at 0% and never end.

**Expected behavior**
The _downloading forge installer_ should end, and the launcher should add the mods to the instance.

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**
![image](https://user-images.githubusercontent.com/57562990/140073946-3be16572-d1f2-4430-a163-1e29405f16f6.png)

**Operating System:**
- OS: Ubuntu
- Version: 20.04.3 LTS
- Java Version: openjdk version "1.8.0_242" and "16.0.1"![image](https://user-images.githubusercontent.com/57562990/140075191-2c30492d-7031-49aa-949b-297e245e4596.png)
- Minecraft Version: all forge versions
- Mod Loader: forge

**Additional context**
When I try to close and relaunch the launcher after seeing that the installation process never ends, I just got these files 
![image](https://user-images.githubusercontent.com/57562990/140076372-842c3ed1-4c82-445a-b729-4ce184c32b08.png)
in the instance folder and I'm not able to launch it.

**Comment by Eskaan** [comment]
Duplicate of #1086
