### ISSUE TITLE
Mac is not allowing GDLauncher to run

### ISSUE THREAD

**Issue by Advik-B** [killpowa/Twickt-Launcher#1148]
**Describe the bug**
Mac is not allowing gdlauncher

**To Reproduce**
- Download GDLauncher for mac.
- Install it
- double click on GDLauncher in the apps folder

**Expected behavior**
- GDLauncher will open and ask for mojang sign-in

**Possible solutions**
Register the app/make it available of apple store

**Screenshots**
<img width="1512" alt="Screenshot 2021-11-04 at 6 18 18 PM" src="https://user-images.githubusercontent.com/86160411/140316148-90a66005-c1e0-4e85-8b08-abf5af37b51e.png">

**Operating System:**
- OS: Mac (Darwin)
- Version: i dont know
- Java Version: 17
- Minecraft Version: n/a
- Mod Loader: n/a

**Comment by Eskaan** [comment]
That’s not the problem. Right click the app and then Ctrl-click „Open“
It will then ask you if you want to open it.
I see a folder named „python“ on your desktop, didn’t you ever open a program that isn’t verified?
Apple wants ~100$/year for verification. If you can afford that we would be very pleased if you donate for that purpose.
Please reply/close this issue if ist resolved now :)

**Comment by Advik-B** [comment]
Well okay then. thanks for solving the problem.

>  If you can afford that we would be very pleased if you donate for that purpose.
> Please reply/close this issue if ist resolve

Wow I guess apple really wants the money hua
I closing this issue since this is not a GDLauncher issue. :-)
-Advik

**Comment by sylvesterroos** [comment]
So Apple disallows you from launching an unverified binary?

**Comment by Advik-B** [comment]
> So Apple disallows you from launching an unverified binary?

Yep
