### ISSUE TITLE
WinGet installation

### ISSUE THREAD

**Issue by rlnt** [killpowa/Twickt-Launcher#1149]
It would be very nice if you offered the installation of the GDLauncher via WinGet.
That would be pretty handy since there isn't much to the installation process anyways.
https://github.com/microsoft/winget-cli

**Comment by huantianad** [comment]
Believe anyone could package stuff for winget if you wanted, so you could do it yourself if you don’t want to wait for us to do it.
~~besides you should try Linux if you like package managers~~

**Comment by rlnt** [comment]
Linux users will always say something like this. They complain about Windows because the lack of Linux features but if Microsoft implements these features, it's also not right. I am happy they finally have a somewhat usable package manger.

I rely a lot on Windows for my work and for the rest I use WSL. No need to try Linux but thanks.

**Comment by huantianad** [comment]
Just joking, I wouldn’t expect people who care about WinGet to switch to Linux. (Rereading this, sounds a bit pretentious, please don’t take it that way)

But returning tot he subject at hand, do you need to be the owner of the software to submit a manifest for WinGet?

**Comment by Eskaan** [comment]
> complain about Windows because the lack of Linux features

I don’t think that’s true because most Linux users just use Linux because
- It has better performance 
- It has more features (as you said)
- It’s open source so it doesn’t steal your data :)

**Comment by russellbanks** [comment]
GDLauncher is on WinGet under `GorillaDevs.GDLauncher`:

```
winget install GorillaDevs.GDLauncher
```

It is also being automatically updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation).

**Comment by Eskaan** [comment]
Thanks 👍
