### ISSUE TITLE
GDlauncher can't download forge installer

### ISSUE THREAD

**Issue by DonTMover** [killpowa/Twickt-Launcher#1150]
Statr Download any forge minecraft package , process stoped on "Downloading forge installe
![GDLauncher_viYzBORX3Q](https://user-images.githubusercontent.com/46960051/140539067-d93e8c89-44d6-4f57-bf7d-c61ffbfdc28b.png)
r"

**Comment by DonTMover** [comment]
I don't cnow , what need's writing ...
I'll just leave it here
OS: WIN 10

**Comment by Eskaan** [comment]
Duplicate of #1086
