### ISSUE TITLE
Implementation of getModerator() for GuildVoiceEvents

### ISSUE THREAD

**Issue by Andre-4949** [killpowa/Twickt-Launcher#1160]
### Is your feature request related to a problem? Please describe.

The feature is not related to a problem, rather to some ideas I made for my Bot which couldn't be fullfilled by neither JDA nor my code (which was a miserable attempt to get the moderator and only worked 40% of the time).

### Describe the solution you'd like

A way to get the moderator, which caused the event for the following events:
- GuildVoiceLeaveEvent
- GuildVoiceMoveEvent
- GuildVoiceGuildMuteEvent
- GuildVoiceGuildDeafenEvent

(If the moderator wasn't the reason for some of these events, setting the value to null would be an option)

### Describe alternatives you've considered

As an alternative of getting the moderator I considered using the AuditLog which worked more or less 40% of the time 

**Additions**
The Getter doesn't need to be named "getModerator()", I am just very bad at naming stuff, that's why i picked the most obvious name i could think of

**Comment by huantianad** [comment]
Are you sure you opened a issue on the right repo?
