### ISSUE TITLE
Cannot load 1.18 Pre-Release 2

### ISSUE THREAD

**Issue by Storyboard-MC** [killpowa/Twickt-Launcher#1163]
**Describe the bug**
The newest Snapshot requires Java 17 to be able to load

**To Reproduce**
1. Install the Newest Snapshot
2. Launch it.
3. And it crashes

**Expected behavior**
It should load the Game

**Possible solutions**
Add compatibility with Java 17

**Screenshots**

**Operating System:**
- OS: [e.g. Windows] Manjaro Linux 
- Version: [e.g. 10] Pahvo 21.1.6 KDE 
- Java Version: [e.g. 8/16] 16
- Minecraft Version: [e.g. 1.16.5] 1.18 Pre-Release 2
- Mod Loader: [e.g. Forge/Fabric] None

**Additional context**

**Comment by TheKodeToad** [comment]
This will probably be fixed when 1.18 is the latest. For now, you can point the Java 16 executable to a Java 17 one.

**Comment by Andre601** [comment]
There is a pre-release of the launcher fixing the Java 17 issue.

**Comment by MoonlightGriffon** [comment]
This seems to be an issue that should probably be raised to a higher priority as 1.18 has been released so this is a problem that lots of people will start noticing shortly.

**Comment by Eskaan** [comment]
This issue is fixed. It just needs to be merged into a stable release

**Comment by egorananyev** [comment]
I'm still getting an error with Forge. I downloaded GDLauncher v1.1.16-beta.3, which automatically installed Java 17 upon launch, but it fails to start a Forge MC. Fabric and Vanilla are fine though.

**Comment by Eskaan** [comment]
Java 17 integration is now included into stable so I will close this (the error mentioned in the comment above is not related to the original issue)
Thanks for doing a good report :)
