### ISSUE TITLE
Clicking on three dots in the instance manager -> mods doesn't do anything

### ISSUE THREAD

**Issue by Peca21** [killpowa/Twickt-Launcher#1173]
**Describe the bug**
I just updated the launcher, clicked on manage for my modpack, clicked check for updates and clicked three dots but nothing happens when I click three dots

**To Reproduce**
1. Go to instance manager
2. Click on mods
3. Click on Check for updates
4. Wait
5. Click on three dots

**Expected behavior**
Menu pops up, allowing me to update all mods

**Possible solutions**
??

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/13818400/143056350-8583b48f-682f-49fc-a4a9-928b7288ffc6.png)

**Operating System:**
- OS: Windows
- Version: 11 Pro x64
- Java Version: Automatic setup 8
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
and yes some mods have updates (download arrow next to the filename)
Started happening after update to 1.1.16-beta.1

**Comment by Eskaan** [comment]
Fixed in v1.1.17+ d58a46d60d118997108a5540cfc88685ba6b19b3
