### ISSUE TITLE
Fails to launch trying to change executable bit

### ISSUE THREAD

**Issue by ShayBox** [killpowa/Twickt-Launcher#1183]
**Describe the bug**
Launcher tries to change executable bit of 7za.  
In cases where the launcher is installed to system directories like `/opt`, it can't.  

**Expected behavior**
The launcher opens

**Possible solutions**
If the file is already executable, don't try to make it executable.  
Also don't crash the program if it fails to make it executable.  
It should crash if it's unable to execute the executable though.  

**Operating System:**
- OS: Arch Linux

**Additional context**
In my case the 7za file is already executable as part of the [install procedure](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=gdlauncher-beta) which installed it in a system directory, but it still tries to change the executable bit.  
It crashes the launcher when it fails to change the executable bit, which shouldn't be the case, it should only crash if it fails to execute the executable, after trying to change the executable bit.  

Additionally, why does the launcher distribute and exclusively use a 7za binary, this should be a dependency, or at-least look for and prioritize 7za in path over the distributed binary.

**Comment by huantianad** [comment]
I did respond to the AUR comment, but for completion, the error when trying to chmod the 7za binary is non-fatal, and does not cause the program to crash. Perhaps it would be beneficial for gd to first check if it's already executable, then only chmod it if it's not.

**Comment by ShayBox** [comment]
Hmm, it seems to work fine today despite the error, but yesterday it was the last output before the program crashed every time... it makes no sense!

**Comment by huantianad** [comment]
It's a common error, often times the linux version will crash on startup which is fixed by a restart. The chmod error is just there to trick you to think that it's the chmod failing causing the crash :wink:

**Comment by egut** [comment]
As for the chmod command

```
File: public/electron.js


    if (process.platform === 'linux' || process.platform === 'darwin') {
      const sevenZipPath = await get7zPath();
      await promisify(exec)(`chmod +x "${sevenZipPath}"`);    # Only one of this line
      await promisify(exec)(`chmod 755 "${sevenZipPath}"`);  # or this line is needed :D
    }
```

**Comment by Eskaan** [comment]
> As for the chmod command

Did you realize it’s in a try catch Block?
