### ISSUE TITLE
Use system default file explorer

### ISSUE THREAD

**Issue by MasterSloth1** [killpowa/Twickt-Launcher#1185]
When I click open folder within the context menu in GDLauncher it opens the folder with windows file explorer.

**Describe the solution you'd like**
For GDLauncher to use the system default file explorer instead of windows file explorer

**Additional context**
OS - Windows 11
I have installed Files [Files Github](https://github.com/files-community/Files)
I have set Files to be my default file explorer following this tutorial here [Files replace file explorer](https://files.community/docs/configuring/replace-file-explorer)
I have also set Files to open when I press Win + E following this tutorial [Win + E replacement](https://files.community/docs/configuring/configure-win-e)

**Comment by TheKodeToad** [comment]
This is most likely an issue with Electron.

**Comment by Eskaan** [comment]
Yes, this is an issue whit Electron. We are telling Electron to open a file selection dialog and Electron returns us the selected path.
