### ISSUE TITLE
Can't start forge 1.18 (IOException)

### ISSUE THREAD

**Issue by Peca21** [killpowa/Twickt-Launcher#1190]
**Describe the bug**
I just downloaded forge 1.18 and it crashes on startup

**To Reproduce**
1. Install 1.18 forge
2. Click on Play

**Expected behavior**
No crash

**Possible solutions**
IDK

**Screenshots**
![image](https://user-images.githubusercontent.com/13818400/144480279-bba2a12e-693a-4cf9-8cf6-4740f450d9b8.png)

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 17
- Minecraft Version: 1.18
- Mod Loader: Forge

**Additional context**
java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [..\..\datastore\libraries\net\minecraft\client\1.18-20211130.085255\client-1.18-20211130.085255-srg.jar, ..\..\datastore\libraries\net\minecraft\client\1.18-20211130.085255\client-1.18-20211130.085255-extra.jar, ..\..\datastore\libraries\net\minecraftforge\forge\1.18-38.0.8\forge-1.18-38.0.8-client.jar]

**Comment by NightHammer1000** [comment]
I can second this.

It seems like something is not getting downloaded right. The Missing File prevents the start.

Tried it on 4 diffrent PCs. Same result everywhere.

**Comment by Mahsaap** [comment]
https://github.com/gorilla-devs/GDLauncher/issues/1189#issuecomment-984768042

**Comment by chrisn1992** [comment]
The Launcher may or may not download the said missing file in the error.
If it downloads, after patching phrase of the download, the launcher removes that file which causes this problem.
There are alot of missing files in logs during installation

**Comment by Eskaan** [comment]
I don’t think the launcher deletes the patched files on itself

**Comment by chrisn1992** [comment]
> I don’t think the launcher deletes the patched files on itself

I did observe the folder and the launcher indeed removes many files which listed error in the log during installation(and they are not existed during instance launching)

**Comment by SoggyDoggy** [comment]
> It seems like something is not getting downloaded right. The Missing File prevents the start.

Can confirm. I saw the same. Can't we just extract it from the original installer to a temporary place and add The Missing File?

**Comment by SoggyDoggy** [comment]
I got it working!  What I did:
1. Download the installer at files.minecraftforge.net/net/minecraftforge/forge/
2. Run the installer and let it install to the default launcher address (C:\Users\*YOURUSERNAME*\AppData\Roaming\.minecraft) which should be the first place it offers you to install it.
3. Go to C:\Users\*YOURUSERNAME*\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1.18-20211130.085255 copy all the files exept the client-1.18-20211130.085255-mappings and paste them to C:\Users\*YOURUSERNAME*\AppData\Roaming\gdlauncher_next\datastore\libraries\net\minecraft\client\1.18-20211130.085255 
4. Now, close and re-open GDLauncher
5. And the instance should work until the next time you try to make another Forge 1.18 instance cause then it will remove those files again and you're gonna have to do the process again from step 3.

**Comment by Eskaan** [comment]
This may be a duplicate of #1189
