### ISSUE TITLE
[1.1.16 Beta.3] unable to install Forge for 1.18

### ISSUE THREAD

**Issue by Bass2style** [killpowa/Twickt-Launcher#1196]
**Describe the bug**
unable to install Forge 1.18 correctly, and obviously launch Forge for 1.18, seems not related to java, fully vanilla instances are working. (should try a Fabric instance, but i'm pretty sure it's related to Forge changes...)

**To Reproduce**
1. create a new 1.18 forge instance
2. wait for install
3. it seems correctly installed, but it can't run.
4. check the launcher console, there are errors when installing, and obviously when you try to launch the instance.

**Expected behavior**
a bugfree install. lul

**Possible solutions**
idk, my knowledge in dev etc is a bit limited.

**Screenshots**
no revelant screenshots.

**Operating System:**
- OS: Windows
- Version: 10 21H1 
- Java Version: Java 8 update 311 installed, but, i use the default provided Java binaries for GDL.
- Minecraft Version: 1.18
- Mod Loader: Forge, any 1.18 build

**Additional context**
providing error log : https://gist.github.com/Bass2style/e6c1bed871ad1075ccdba3308f4fa0ee

scénario of the actual log : launched GDL, opened the actual instance profile, and updated Forge, and directly when updated, i launched the instance, so, both errors (update + launch) are present in this log.

edit : new log

i created a fully new instance of Forge 1.18, without launching or updating, here is the log : https://gist.github.com/Bass2style/3ed47fe4a08a3964f26e192c2c10cb0f

tryed a Fabric instance, and it's working, so, definitly a Forge related issue.
forge instances creation/launch on another well known launcher (not Curse) are working, so it's how GDL manage Forge's installer i think.

**Comment by Rustypredator** [comment]
I Can Reproduce the bug with 1.1.6-beta,3  on Linux Kernel 5.15.6  
  
However, as mentioned in #1195 this issue can be "fixed" by copying the libraries folder of an installed forge client over to the datastore folder.

Relevant Error messages including the expected library path: [error log](https://gist.github.com/Rustypredator/c026cfffae759207b25c3a23faa13555)

**Comment by Bass2style** [comment]
trying on Linux when my VM is ready, it can also be a Windows-only issue.

it's more a temporary workaround than a real fix btw, at every Forge update i need to proceed this everytime, but, it's for the moment a solution that i can try. 

edit : can't try on Linux, my brand new Ubuntu VM wan't to run GDL. xD
edit2 : rebooted my VM, seems launching now.
edit3 : same issue on a Ubuntu VM, so, still an issue on how GDL manages Forge installer.

**Comment by Bass2style** [comment]
seems fixed in GDL 1.1.18, i need to wait update for mods, a lot of them are still 1.8(.0), and don't work on 1.8.1.
for the moment, i have no errors anymore when updating/installing forge, so i'm closing the report for now.
