### ISSUE TITLE
File for Forge did not get downloaded

### ISSUE THREAD

**Issue by schockocraft** [killpowa/Twickt-Launcher#1203]
**Describe the bug**
After Newly installing this launcher i set up the first instance and had it download. Because of my slow internet that took 40 minutes or so, but instead of finishing the download then it stuck on 99%. I waited for another one and a half hours in which the launcher did not show any internet access or hdd access in taskmgr whenever i looked, so i decided to restart the launcher. The instance then appeared correctly, but clicking on it only gives me an `asyncToGenerator.js:6 Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\gdlauncher_next\datastore\libraries\net\minecraftforge\1.12.2-14.23.5.2857\1.12.2-14.23.5.2857.json'` error in the console.

**To Reproduce**
1. Freshly install GD
2. Set up a new instance
3. Wait for GD to download most files
4. Have GD stop and not attempt to finish the download over more then an hour
5. Restart GD

**Expected behavior**
The Download does not hang up.
OR
The Launcher finishes the Download after restart

**Possible solutions**
A potential "repair instance" button in the manage instance ui, that makes GD recheck the files and download missing ones would fix the problem if it ever occurs again. For now i'd just need any possibility to get the missing file, ideally without doing the whole download again.

I also have the forge version already installed in MMC, so if i can move files over from them to make it work that would also solve the problem for me

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8
- Minecraft Version: 1.12.2
- Mod Loader: Forge 14.23.5.2857

**Additional context**
I have a slow internet connection in general, but the connection was only used by GD.

**Comment by NightHammer1000** [comment]
You can just go to Modpack in the Instance Settings and redownload the same version. Thats how I Repair on download fails.

**Comment by schockocraft** [comment]
> You can just go to Modpack in the Instance Settings and redownload the same version. Thats how I Repair on download fails.

The problem is that it was my own custom modpack, that i already had working in MMC, so what i had GD download was just vanilla with forge, and then i moved all the mod jars over manually (Remember slow internet, so redownloading all the jars would've taken ages).
In the end i managed to fix it by downgrading the forge version, and then upgrading it again, then GD noticed that it didn't have that forge version.

**Comment by Eskaan** [comment]
Maybe your download got corrupted because of your slow internet (just an Idea)
We added a "repair" button in v1.1.20 so you can just let the launcher redownload the missing files for exact such cases.
