### ISSUE TITLE
GDLancher doesn't allow me to create instance

### ISSUE THREAD

**Issue by ZizoPlayz** [killpowa/Twickt-Launcher#1205]
Hello, I recently found out about gdlancher. When I can to add a new instance an error pops up.

![image](https://user-images.githubusercontent.com/95354958/145695609-dd2928f3-273d-414f-8821-2bbeb13427fe.png)

**Comment by Eskaan** [comment]
On which version of the Launcher are you?
On which OS are you?
Does the issue still persist?

**Comment by ZizoPlayz** [comment]
This was on Windows 10 but this issue doesn’t persist. The issue was from my end. The launcher couldn’t access the Minecraft files.  This was on 1.18 version.

Zaid Elzeftawi

**Comment by Eskaan** [comment]
👍
