### ISSUE TITLE
openjdk8.json throwing timeouts on launch after latest update

### ISSUE THREAD

**Issue by DanielSeldura** [killpowa/Twickt-Launcher#1212]
**Describe the bug**
After updating by clicking the green upgrade icon, the launcher is forever stuck on "loading"

**To Reproduce**
Open the launcher, get stuck forever. Click the logs icon to see more.

**Possible solutions**
Check the url for openjdk8, there may be an issue there

![image](https://user-images.githubusercontent.com/16881329/146189741-a086bddf-77a2-4bfd-8752-d75121ca6d2c.png)

![image](https://user-images.githubusercontent.com/16881329/146189779-dae6b7a0-3b98-4ed9-80c6-a7e56fc757ea.png)

**Operating System:**
- OS: Windows
- Version 10
- Java Version: irrelevant
- Minecraft Version: irrelevant
- Mod Loader: irrelevant

**Comment by blarfoon** [comment]
Fixed in 1.1.20
