### ISSUE TITLE
Error occurred while fetching token from Xbox Secure Token Service

### ISSUE THREAD

**Issue by Reeses-Puffs** [killpowa/Twickt-Launcher#1214]
**Describe the bug**
I tried installing GD Launcher, and on the login screen I chose to login with my microsoft account. The credentials are all correct, but after attempting to log in I get the error message mentioned in the title.

**To Reproduce**
1. Run the GD Launcher installer
2. Click on "sign in with microsoft" after doing java setup (I use JDK 17 from adoptium)
3. Attempt to log into your account
4. Error: Error occurred while fetching token from Xbox Secure Token Service.

**Expected behavior**
GD Launcher should log into my microsoft account and proceed as normal.

**Possible solutions**
I'm sorry, I don't know anything about how networking and authentication works.

**Screenshots**
![Screenshot (226)](https://user-images.githubusercontent.com/73549793/146465452-750e03ed-3aea-4a03-900c-4c4c3bc582ac.png)

**Operating System:**

- OS: Windows 10 Home
- Version: 21H1
- Java Version: Adoptium JDK 17
- Minecraft Version: n/a
- Mod Loader: n/a

**Additional context**
I recently changed my microsoft account password, so that might be contributing to the problem. Though I could log in just fine on the official launcher.

**Comment by Jeremy-Stafford** [comment]
I am experiencing the same issue on Fedora, using GD Launcher v1.1.18.

**Comment by Eskaan** [comment]
To cite our Discord FAQ:
> MS accounts under 18 will get "Error occurred while fetching token from Xbox Secure Token Service" when trying to login on 3rd party launchers atm with the current login system being used by them.
Possible workaround is having an adult setup family group (unconfirmed) https://account.microsoft.com/family/about
>
> Microsoft accounts without a linked Xbox profile will also get "Error occurred while fetching token from Xbox Secure Token Service". Sign in  to your Microsoft account and create one here.
https://account.microsoft.com/profile
Down at the bottom click the Xbox profile 

This is a well known issue for us but unfortunately we can't do very much about it, it's on Microsofts side.

**Comment by ghost** [comment]
You need to setup xbox account, and the nickname for java minecraft in the minecraft cabinet. After that it works.
