### ISSUE TITLE
Any instance won't launch, stuck loading.

### ISSUE THREAD

**Issue by protoelectric** [killpowa/Twickt-Launcher#1215]
**Describe the bug**
Whenever launching an instance, it gets stuck on the "Your instance is starting screen". Clicking off of said screen will just show the loading icon on the instance forever.

**To Reproduce**
1. Launch any instance
2. See issue

**Expected behavior**
For the instance to launch

**Possible solutions**

**Screenshots**

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
Tried java 8, 11, 16
re-installed gdlauncher
tried all instances 

(This also happens with using other launchers such as MultiMC or even the default launcher. Instance launches, but never shows up.)

**Comment by protoelectric** [comment]
Quick update:

It does launch, but about 15 minutes after starting, even if gdlauncher is closed. I was able to reproduce this twice.

**Comment by Eskaan** [comment]
Duplicate of #1193
