### ISSUE TITLE
Stuck on loading launcher

### ISSUE THREAD

**Issue by TrainDoesGames** [killpowa/Twickt-Launcher#1218]
**Describe the bug**
The launcher will not load and is stuck on the loading screen after update

**To Reproduce**
Start the launcher

**Expected behavior**
The launcher to load

**Possible solutions**
None

**Screenshots**
Unavailable

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 11
- Minecraft Version: 1.16.5
- Mod Loader: forge

**Additional context**

**Comment by DwarfDolphin** [comment]
I was also about to post about this. The launcher is stuck on the loading screen when I open it. 
But hey, I get to stare at that cool loading screen for a while /s

**Comment by SingerJonathan** [comment]
Same happening to me using the v1.1.19 .AppImage on Arch Linux. v1.1.18 is still working fine.

This error appears in the console when starting the launcher.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'version_data')
    at index.js:340
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at index.js:318
    at DesktopRoot.js:87
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

**Comment by blarfoon** [comment]
Sorry about this, it was caused by an issue with our cdn. Could you please try again now?

**Comment by ZizoPlayz** [comment]
Do I  try to install GDlauncher once more

**Comment by thedarkcolour** [comment]
I'm getting the error still

**Comment by ZizoPlayz** [comment]
![image](https://user-images.githubusercontent.com/95354958/146978191-e0f99207-31a8-4edf-9884-372ada728b1f.png)

**Comment by TrainDoesGames** [comment]
> Sorry about this, it was caused by an issue with our cdn. Could you please try again now?

it works!

**Comment by blarfoon** [comment]
I just purged the cache. You might need to wait for your local cache to invalidate, it should take around 24h. If you want to do it immediately you can follow these steps:
![image](https://user-images.githubusercontent.com/10165264/146978796-db4a73b1-0a76-4d4e-9c02-33bbb8345cff.png)
![image](https://user-images.githubusercontent.com/10165264/146978819-cb58aa50-c10c-448b-87b7-77c6d78f72da.png)
![image](https://user-images.githubusercontent.com/10165264/146978836-4098952b-c853-490d-bef7-bfbda034625a.png)
and then restart the launcher

**Comment by SingerJonathan** [comment]
> I just purged the cache. You might need to wait for your local cache to invalidate, it should take around 24h. If you want to do it immediately you can follow these steps:
. . .

This didn't work for me. What did work is deleting the "Cache", "Code Cache" and "GPUCache" folders in "/home/username/.config/gdlauncher_next" (or "C:/Users/username/AppData/Roaming/gdlauncher_next" for Windows). I had to log in again afterwards, but everything else is as it was. Probably not necessary to delete all three folders, but I got rid of them all just to be safe.

**Comment by blarfoon** [comment]
Yeah, that works too!

**Comment by thelastcheetah** [comment]
i tried everything and still it is not working :(

**Comment by Teapot4195** [comment]
Given how old this problem is it may be a good idea to open a new issue. @thelastcheetah
