### ISSUE TITLE
Can't Open Resource Packs Folder from Minecraft

### ISSUE THREAD

**Issue by luckyboy66666666** [killpowa/Twickt-Launcher#1236]
**Describe the bug**
When I try to apply a resource pack for my Minecraft Forge 1.12.2 installation, my computer flashes the message "Windows cannot find 'C:\Users\[uname]\AppData\Roaming\gdlauncher_next\instances\Forge 1.12.2\..\..\instances\Forge 1.12.2\resourcepacks'. Make sure you typed the name correctly, and then try again." It seems like the installation is trying to go up two directories in the middle, which freaks my computer out.

**To Reproduce**
1. In the main menu, click on "Options" and then "Resource Packs".
2. Click on "Open Resource Pack Folder".
3. The error presents itself almost immediately.

**Expected behavior**
I would see the resource pack folder corresponding to the current installation with all of my resource packs in it.

**Possible solutions**
None that come to _my_ mind (at least, none that don't just say "fix it"). I would think this should be a simple fix and I would hope that the error comes _only_ from the path being entered incorrectly, but that rarely seems to be the issue, especially with something like "\\..\\..\\".

**Screenshots**
![Error](https://user-images.githubusercontent.com/55466006/147775386-5f14f44c-2acc-4d26-aaf5-dde0f27f2710.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8
- Minecraft Version: 1.12.2
- Mod Loader: Forge

**Comment by nsde** [comment]
Same!

**Comment by WolfBV** [comment]
Have you been able to resolve your issue? If so, what was your solution?

**Comment by Eskaan** [comment]
Also a dup of #991, thanks for @WolfBV for finding all these.

**Comment by luckyboy66666666** [comment]
> Have you been able to resolve your issue? If so, what was your solution?

To be honest, I haven't used GDL in a while. I've moved over to Linux, as it gets better performance there, and found the Prism Launcher to be adequate for my needs. I imagine your fix would have worked fine though (installing the portable version) if I had thought of it.
