### ISSUE TITLE
Vivecraft Support

### ISSUE THREAD

**Issue by mecwerks** [killpowa/Twickt-Launcher#1243]
**Is your feature request related to a problem? Please describe.**
Currently, there doesn't seem to be a way to manually install vivecraft. I've convinced multiple of my friends to use GDLauncher and would like a way to be able to add Vivecraft so that they can see custom animations and such.

**Describe the solution you'd like**
Perhaps a toggle of some sort in the manage tab, or a custom loader profile to support it.
Even a way to manually edit the instance and install Vivecraft would be nice and potentially? less work.

**Describe alternatives you've considered**
The only alternatives to get it working are to use MultiMC or the default launcher.

**Additional context**
The only problems I can see at the moment, is using a launcher profile, I don't know if it would work to save that info when uploading/downloading a modpack. I think a toggle on supported forge versions would be best that can just be ticked on after downloading a pack.

**Comment by mecwerks** [comment]
Note: I did see issues #775 and #1230, but I thought creating a new issue would bring more attention to the request. Sorry in advanced.

**Comment by Eskaan** [comment]
Well yes, its a duplicate (closing it) but you got my attention.
