### ISSUE TITLE
Can't install modpacks: 400 and 504 errors

### ISSUE THREAD

**Issue by atlgeek007** [killpowa/Twickt-Launcher#1246]
No matter what modpack I try to install, it just spins at "downloading mods" and the console has 400 and 504 errors.
![Screenshot 2022-01-08 162157](https://user-images.githubusercontent.com/3845395/148660450-26894e22-2736-4889-9340-d9d96f594497.png)

**Comment by RobinVanCauter** [comment]
Having the exact same issue when trying to update a modpack.

**Comment by DryChicken47** [comment]
I'm experiencing the same issue here, no chance to download or even launch modpacks.

**Comment by Eskaan** [comment]
Duplicate of #1154
