### ISSUE TITLE
Sign in with Microsoft broken

### ISSUE THREAD

**Issue by zilqnova** [killpowa/Twickt-Launcher#1247]
**Describe the bug**
When attempting to sign in to GDLauncher through Microsoft, I receive the message "Error: Error occurred while fetching token from Xbox Secure Token Service." I am not able to progress past the login screen.
**To Reproduce**
1. Go to login screen
2. Click on Sign in with Microsoft
3. Enter login credentials and allow access

**Expected behavior**
I expected to, upon going through the Microsoft Sign in dialog, be logged into the client and be able to use it. However, upon completing the dialog, I am instead brought to a brief loading screen and kicked back out into the login screen with the error message.
**Possible solutions**
Someone recommended I try a "bleeding-edge" build of the client through the options and see if the bug was fixed there; however, I cannot access client options from the login screen. Maybe there is simply some issue with Microsoft's servers right now, but I logged into the official Minecraft client not too long before. I also don't know if there are newer "beta" builds I could build from source on GitHub, but it doesn't appear that way.

**Screenshots**
![image](https://user-images.githubusercontent.com/86683826/148661813-a718ac9e-8319-4f8a-aafb-0cf4a27f400e.png)

**Operating System:**
- OS: Arch Linux
- Version: 5.15.13-arch1-1
- Java Version: 17
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
I am unsure if this is a problem exclusive to Linux or if this also occurs on WIndows. I would assume that it is a Linux-specific issue, however.

**Comment by Eskaan** [comment]
To refer our Discord FAQ:

>Q: I can not login with my Microsoft account. How do I login?
>
>A:
>- First off you have to have bought Minecraft Java Edition.
Minecraft Windows 10 Edition (bedrock) is not the same and will not work.
https://www.minecraft.net/en-us/store/minecraft-java-edition
>
>- Download the beta from the release page and you will have Microsoft (MS) login as an option:
https://github.com/gorilla-devs/GDLauncher/releases
windows os use: GDLauncher-win-setup.exe to install or GDLauncher-win-portable.zip
>
>- Windows
since people don't know how to read...
https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-win-setup.exe
>
>In %appdata%\gdlauncher_next folder replace rChannel file with this one.
https://cdn.discordapp.com/attachments/422172396502515715/795785466933936208/rChannel
>
>- After your logged into GDL, go into the settings (gear icon top right) and change the release channel to beta. If you don't do this it will revert to the stable build that currently does not have MS login.
>
>- MS accounts under 18 will get "Error occurred while fetching token from Xbox Secure Token Service" when trying to login on 3rd party launchers atm with the current login system being used by them.
Possible workaround is having an adult setup family group (unconfirmed) https://account.microsoft.com/family/about
>
>Microsoft accounts without a linked Xbox profile will also get "Error occurred while fetching token from Xbox Secure >Token Service". Sign in to your Microsoft account and create one here.
>https://account.microsoft.com/profile
>Down at the bottom click the Xbox profile

Also Duplicate of #1116

**Comment by Eskaan** [comment]
Please reopen this issue if it still persists after following these steps

**Comment by zilqnova** [comment]
I changed my date of birth and it works now.

**Comment by Canpake59** [comment]
I am getting this issue now, but my profile is over 18. It was working fine the other day.

**Comment by blarfoon** [comment]
https://support.xbox.com/en-US/xbox-live-status


Xbox is currently not working
