### ISSUE TITLE
Mod loading stuck at 0%

### ISSUE THREAD

**Issue by Grayhannah** [killpowa/Twickt-Launcher#1249]
Certain mod packs such as Better Minecraft do not download the mods it is always stuck at 0%. After trying to update the Better Minecraft modpack, it was stuck at 0%, I tried to delete and re-download the modpack multiple time, as well as deleting and reinstalling the launcher nothing seems to work, I have done all that I can think of such as clearing the instances as well. Nothing works.

**Operating System:**
- OS: Macos
- Version: [10.13.6]
- Java Version: [8]
- Minecraft Version: [1.16.5]
- Mod Loader: [Forge]
<img width="1680" alt="Screen Shot 2022-01-10 at 4 11 59 PM" src="https://user-images.githubusercontent.com/97481681/148847370-fc498987-0f0e-4bd6-a186-b22262c1656a.png">

**Comment by Eskaan** [comment]
Did you even look at the pinned issues?

**Comment by OveR1337XD** [comment]
Same here 😨

**Comment by Eskaan** [comment]
Duplicate of #1154
