### ISSUE TITLE
[FR] Add play/launch button to the instance manager

### ISSUE THREAD

**Issue by ghost** [killpowa/Twickt-Launcher#1250]
**Is your feature request related to a problem? Please describe.**
When troubleshooting, bug hunting with mod conflicts, or updating mods, it is quite annoying to have to keep exiting the instance manager gui, go back to the instance screen, locate the instance, launch, close instance, right click, manage instance, add/enable/update mod, close instance menu and repeat ad nauseam.

**Describe the solution you'd like**
I'd love if you could add a launch button in the left menu below the instance icon or at the lower left corner.  

It would make prototyping and testing easier when quickly enabling/disabling/adding/updating mods with many instances created on my instance screen as I wouldn't need to repeatedly traverse through as many levels of UI or try and grok the cluttered visual mess that is my instance list.

**Describe alternatives you've considered**
See previous.

**Additional context**
![image](https://user-images.githubusercontent.com/38839287/149013352-e69a6a9a-8cd2-4cc1-b8de-4391210cdc63.png)

**Comment by ghost** [comment]
https://github.com/gorilla-devs/GDLauncher/commit/453eb4a7d65744754242b61a38aa32a3f80faaef
Logged in today and noticed your awesome work @killpowa thanks!
It seems like it functions appropriately, although it may need a slight UX tweak, the play button looks a bit of an ambiguous "interactive green" when running, the only indicator that it isn't is the on hover cursor style.

Possible suggestions for it:
* mute the green color like the red is when not interactive during/after the launch spinner (could be a tad odd looking perhaps? very cassette player-ish, but gets the point across)
* modify the button on run state change to represent the only possible action as an instance is either stopped, launching, or running at any given time (the right click instance menu for example doesn't show kill when the instance is not running/launching)

![image](https://user-images.githubusercontent.com/38839287/154207827-aa34cb63-906d-410e-9dc5-c6f94a92047c.png)
![image](https://user-images.githubusercontent.com/38839287/154207862-0d162f1f-3077-4b27-a82a-278bbaa93e70.png)
![image](https://user-images.githubusercontent.com/38839287/154207894-974bfb4e-fd49-46f4-a5eb-2da56deed947.png)

Thanks again!

**Comment by Eskaan** [comment]
Got it in 453eb4a7d65744754242b61a38aa32a3f80faaef
