### ISSUE TITLE
cannot download mods with gdlauncher

### ISSUE THREAD

**Issue by DragonWoven** [killpowa/Twickt-Launcher#1252]
Describe the bug

after clicking the add mods button it doesn't show the list of mods and while searching the mods will show up then disappear with an error

To Reproduce

1. create a fresh fabric instance 
2. go to the mods manger and click add mod

Expected behavior

be able to seen and add mods without error

Screenshots

![image](https://user-images.githubusercontent.com/84992486/149248400-3e1ae12f-b73a-4820-993a-27db4bf40daa.png)

**Operating System:**
- OS: Windows 11 and Windows 10
- Version: 1.1.21
- Java Version: 17
- Minecraft Version: 1.18.1 and 1.17.1
- Mod Loader: Fabric

**Comment by DragonWoven** [comment]
found answer on discord

**Comment by Eskaan** [comment]
(Thx, rare that ppl are closing issues on themselves)
