### ISSUE TITLE
Modpack does not download Mods

### ISSUE THREAD

**Issue by Darudas** [killpowa/Twickt-Launcher#1255]
**Describe the bug**
I tryed downloading a [modpack](https://www.curseforge.com/minecraft/modpacks/crif2) (cursedforge) and it stoped the download as in my screenshot visible. 

**To Reproduce**
!!

**Expected behavior**
a complete download of the modpack and i also tryed the repair function but still same issue

**Possible solutions**
???

![image](https://user-images.githubusercontent.com/52368369/149625964-126b3b4f-17d8-442e-a54b-68c6971404d7.png)
![image](https://user-images.githubusercontent.com/52368369/149626248-dc870911-07d5-4f0a-b1b8-636ce09013ab.png)

**Operating System:**
- OS:  Windows
- Version:  10
- Java Version: [e.g. 8/16]
- Minecraft Version: 1.8
- Mod Loader: Forge

**Additional context**
pls help

**Comment by Darudas** [comment]
i tryed to repair the pack with closed google chrome and i got this here this time 
![image](https://user-images.githubusercontent.com/52368369/149626622-412f081f-7845-4a85-a794-0b06a941fbf6.png)
![image](https://user-images.githubusercontent.com/52368369/149626633-962c76e5-de2c-40b1-bdfb-a56569482094.png)

**Comment by Eskaan** [comment]
Duplicate of #1154
