### ISSUE TITLE
[Bug] Can't open pack folder / any explorer in generall 

### ISSUE THREAD

**Issue by nsde** [killpowa/Twickt-Launcher#1262]
**Describe the bug**
When trying to open the pack folder using the ingame-menu/options, nothing happens. It's just as the button did nothing.

**To Reproduce**
1. Options...
2. Resource Packs...
3. Open Pack Folder
4. Nothing happens!

Same goes for the Iris shader open-pack-folder thingy:
1. Options...
2. Video Settings...
3. Shader Packs
4. Open Shader Pack Folder
4. Nothing happens!

**Expected behavior**

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
- OS: Linux/Pop!_OS
- Version: GDLauncher 1.1.21
- Java Version: 17
- Minecraft Version: 1.18.1
- Mod Loader: Fabric/probably same for vanilla!

**Additional context**
I can hear the click sound.

**Comment by nsde** [comment]
Same as #1236

**Comment by nsde** [comment]
It works fine on MultiMC, though, so it's definitely a GDLauncher issue.

**Comment by WolfBV** [comment]
Have you been able to resolve your issue? If so, what was your solution?

**Comment by nsde** [comment]
I'm on v.1.1.30, the newest version.

**Comment by nsde** [comment]
Lemme check real quick

**Comment by nsde** [comment]
Seems fixed now.

**Comment by Eskaan** [comment]
Dup of #991 btw.
