### ISSUE TITLE
Can't download any modpack.

### ISSUE THREAD

**Issue by Oskal79** [killpowa/Twickt-Launcher#1264]
I have a problem with loading modpaks, it comes to downloading mods and hangs, then 0% then by 96-99%.
I tried different Internet providers, different computers and operating systems (Linux, Windows, Mac OS) all the same everywhere. However, in the official CurseForge lounger, everything is downloaded the first time, but I don’t like their lounger because it downloads the official lounger, there is also advertising and, in principle, it works poorly in all other places (except downloads).
Maybe someone came across and knows the solution to this problem?

Console :
![GDLauncher_2gTuAT1yIo](https://user-images.githubusercontent.com/23283921/151012066-d24e5229-daad-463f-8fe9-6b66b7b5f068.png)

**Comment by Frikkle** [comment]
I have the exact same issue.

**Comment by Eskaan** [comment]
Duplicate of #1154 - There is a reason why it is pinned.
