### ISSUE TITLE
GDLauncher makes my computer completely freeze

### ISSUE THREAD

**Issue by Hund** [killpowa/Twickt-Launcher#1267]
**Describe the bug**

I'm new to GDLauncher and would like to use it, as it looks like a good launcher. The issue is that it makes my computer freeze when I'm trying to download some mods to my new instance that I haven't even launched yet.

The freezes doesn't happen every time, but enough to be annoying. The only thing I can do is to kill the power to the computer.

**To Reproduce**

1. Launch GDLauncher.
2. Manage any instance.
3. Add mods.
4. Watch everything freeze up.

**Operating System:**

- OS: Fedora Linux 35
- Java Version: 17.0.1.0.12
- Minecraft Version: 1.16.5 and 1.18.
- Mod Loader: Both Forge and Fabric

**Additional context**

I'm currently using the AppImage, version 1.1.21. I'm going to try the RPM package and keep a close eye on the memory usage. I have 16 GB of RAM and my system uses less than 1 GB of RAM, so it should be more than enough RAM left for GDLauncher.

**Comment by AshtakaOOf** [comment]
So how much mods did you add ?

**Comment by Hund** [comment]
I had totally forgotten about this issue. It wasn't GDLaunchers fault at all. It was my graphics drivers who was to blame for it.
