### ISSUE TITLE
Failed update should not delete instance

### ISSUE THREAD

**Issue by wcomartin** [killpowa/Twickt-Launcher#1288]
**Describe the bug**
When updating a pack, if the update fails it deletes the instance.

**Expected behavior / Possible solutions**
A better solution might be to mark the instance as corrupted so that the user has a last chance to backup the world files. and try to perform the update again or recreate the instance.

**Operating System:**
- OS: Windows
- Version: 10

**Comment by ccrvincent** [comment]
With the CurseForge API issue, this is even more critical.  I just lost my testing world and a pile of screenshots of an in-progress build because one of the mods in the pack opted out of the new API.

**Comment by Eskaan** [comment]
I think it is fixed - https://github.com/gorilla-devs/GDLauncher/blob/master/src/common/modals/InstanceDownloadFailed.js#L31
Just waiting for confirmation from @Ladvace

**Comment by Ladvace** [comment]
let's see if somebody gets the same error, honestly It should be fixed but I'm not sure.

**Comment by Mr-Oca** [comment]
Looks like I just had the same issue :
I updated Vault Hunter Modpack and GDLauncher as well.
When I tried to launch the modpack, I had an error.
I "repaired" the modpack then launchedit again.
No more mod nore world in the modepack (not even in the folders).
Can I do something to recover it ?

**Comment by ccrvincent** [comment]
When it happened to me, I restored the folder from my cloud backup.

**Comment by Eskaan** [comment]
Repairing an instance should not delete any saves whatsoever. It just tries to fix the gamefiles (which are in an entirely different folder btw). This issue only affects pressing cancel after some error (it seems like it was fixed in a newer version tho).

**Comment by Dasffion** [comment]
I just had this happen to me, wiped 3 days worth of progress on Astropolis. 
![image](https://user-images.githubusercontent.com/43814155/201357750-9dead261-b7fe-4600-b310-5a8493c9e1f8.png)
Got the above error, retired twice, still got the same error, canceled download waited 5 minutes but seemed like it was hung so I closed GDLauncher. When I opened back up I tried to update again and it wasn't finding any versions to update. I opened the instance folder and to my horror this was all that was in there
![image](https://user-images.githubusercontent.com/43814155/201358155-445a0a04-c5b2-4a5e-8c28-2e51078d173c.png)
I'm not sure why, with no option to create a new profile when updating, it's completely wiping the instance.

**Comment by Francois4499** [comment]
Hello I also lost my world, I had to close the game via the task manager because it had crashed. When I restarted it I had an error coming from a corrupted config file so I used the "Repair" option of GD LAUNCHER but it crashed (see picture below) and it destroyed all the game files because when I click on "cancel download" nothing happens for hours! 

I don't say thank you for the tens of hours lost :(


![image](https://user-images.githubusercontent.com/57407928/203131260-8defc51b-e648-4c1d-83bc-18029915a376.png)
![image](https://user-images.githubusercontent.com/57407928/203131337-2dc9b7a2-ec23-4f63-acd1-cbc69e16aa21.png)
The button stays gray like this forever 
![image](https://user-images.githubusercontent.com/57407928/203132100-6c6c1e4c-f3be-4c43-9959-6e8de057d92b.png)

**Comment by Chifilly** [comment]
I just had this happen to me. Lost a weeks worth of progress in Roguelike Adventures and Dungeons 2, which is beyond frustrating! Why on earth would it just wipe out an instance when a download is cancelled?! Surely it should at least _move_ it to a different place temporarily or something...

I was trying to update the modpack but I was stuck on the Cloudflare page when trying to download opted-out mods, so I cancelled the download after a while and it just hung, so closed GDL and found out the instance had been wiped when trying to launch it.

**Comment by cobalt2727** [comment]
Just had this happen to me - this is a serious enough bug that I really can't recommend GDLauncher to people any more. There is no reason a modpack update should be touching configuration data or worlds.

**Comment by Jbz797** [comment]
I am disgusted I just lost my save this way. Is there really no way to get it back?

**Comment by ccrvincent** [comment]
> I am disgusted I just lost my save this way. Is there really no way to get it back?

My backup software (CrashPlan) had a copy of my instance and save.  Check your backup software?

(Disclaimer: I am an engineer at CrashPlan.)

**Comment by Jbz797** [comment]
I don't have

**Comment by Jbz797** [comment]
I'm on a Mac I don't need a backup I never have a problem. Only my documents and photos are backed up in the cloud. 

What an idea to delete a backup like that ... it was a game I had with my daughter for a long time. I just wanted to upgrade to 1.19.3 forge, I got an error and then I lost everything.

We're not going to play Minecraft again.

**Comment by blarfoon** [comment]
I’m so sorry if you lost any of your saves, I am not currently available to do any bug fix, but I’ll make sure to post an announcement in the launcher asap to let people know about this issue.
You could try to recover your saves using a recovery tool like recuva.
Please feel free to contact me in private on discord if you need help trying to recover the data.

**Comment by cobalt2727** [comment]
I'd recommend everyone affected by this try out [Prism Launcher](https://github.com/PrismLauncher/PrismLauncher/releases/latest) for an alternative with a slightly less intuitive UI that _**won't**_ completely trash your data - the feature set is mostly identical, with the exception being you have to [install Java 17 yourself](https://prismlauncher.org/wiki/getting-started/installing-java/) in most cases.

**Comment by SteveMcKoy** [comment]
Just happened with me as well on my several hundred hour DJ2 world, is there really no way to get those files back at all?

**Comment by blarfoon** [comment]
I'm sorry @SteveMcKoy. I don't know exactly the cause or repercussions of this bug. You can contact me on discord (@Davide#1234) and we can try to recover it.

As for the other people, I published a temporary announcement on the launcher so that other people don't incur into this problem

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/10165264/212564916-8cb77748-c224-46c9-a3da-a26f875e4692.png">
