### ISSUE TITLE
Asking for smart card at startup

### ISSUE THREAD

**Issue by Techrese** [killpowa/Twickt-Launcher#1294]
I'm using gdlauncher v1.1.21

Every time when starting the gd launcher i get a windows popup with smart card identification of my yubico key.

I do have one which I use for authentication but not in gdlauncher.

I assume that gdlauncher executes something that triggers the yubico key to go active.

![image](https://user-images.githubusercontent.com/20265461/159243071-191e084b-0c10-4298-a6d8-1c17e5d352d9.png)

**Comment by soulhax** [comment]
+1

**Comment by Eskaan** [comment]
Duplicate of #1124
