### ISSUE TITLE
Compiled Launcher Gives Error At First Startup

### ISSUE THREAD

**Issue by Guestion** [killpowa/Twickt-Launcher#1295]
**Describe the bug**
I'm trying to compile the launcher from the git repo (I cloned it to the GitHub desktop app, 
then opened git bash in the GDLauncher folder, then I followed the compiling steps), 

But when I have it compiled and launch it for the first time it gives me an error stating that
%appdata%\gdlauncher_next\rChannel does not exist

I installed the dependencies,
I cloned the repo,
I ran git bash (MINGW64) in the gdlauncher folder,
I entered npm i,
Then I entered npm run release

It compiles, but then when I go to the deploy folder and use the launcher I get an error
the first time around, when I run it again it tells me gdlauncher is running and to close it,
I close it and it goes ahead and finishes installation

**To Reproduce**
1. Compile Repo
2. Start launcher
3. See error

**Expected behavior**
Expected to install

**Screenshots**
![issue](https://user-images.githubusercontent.com/102258829/159794737-d6c2aa4b-483b-40d0-88b3-9928ab9ebb76.PNG)

**Operating System:**
- OS: Windows 10 Pro
- Version: 10
- Java Version: N/A (But I do have Java 8 & Java 17)
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
It's probably because I'm not 100% sure of what I'm doing
(I'm new to github but trying to learn)

**Comment by Eskaan** [comment]
Ever thought of just adding the file? I don`t really know why its missing but just adding it (its a raw text file containing either a one or a zero) would have fixed it. I expect you didn't run GDL ever before. What happened it that it creates the rchannel file along with the gdlauncher_next folder. through killing it, you interrupted that.
