### ISSUE TITLE
Modrinth modpack export/toggle instance path

### ISSUE THREAD

**Issue by obewi** [killpowa/Twickt-Launcher#1297]
**Is your feature request related to a problem? Please describe.**
No, it's just annoying, I have a modpack and would like it to export in a modrinth format ([docs](https://docs.modrinth.com/docs/modpacks/format_definition/) are out) and I have a tool for that called [packwiz](https://github.com/packwiz/packwiz) and i wanted to put the modpack in my documents folder (because its way easier to navigate to that in the command line) but I can't do that. 

**Describe the solution you'd like**
Add the modrinth export format

**Describe alternatives you've considered**
Add a toggle for a custom path to your mc instance like the toggle for the java path

**Comment by Eskaan** [comment]
Duplicate of #768
