### ISSUE TITLE
EnviroEnergy not downloading from CurseForge properly

### ISSUE THREAD

**Issue by ysnt-yes** [killpowa/Twickt-Launcher#1301]
**Describe the bug**
EnviroEnergy not downloading with packs.

https://www.curseforge.com/minecraft/mc-mods/environmental-energy

**To Reproduce**
Download any curseforge pack with the mod.
I personally tried Ragnamod 6 and ATM 6

**Possible solutions**
I noticed one of the "public" download links on their curseforge page was 404'd so it might have moved, mod downloads fine in regular curseforge.

**Operating System:**
- OS: win10
- Java Version: OpenJDK  that comes with launcher
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
Not many other than I've had it happen with a few friends the past couple days, we can add the mod in after-the-fact and it's fine. For some reason it's just that mod it seems.

**Comment by Mari023** [comment]
It might be possible that they turned of the Option to "Allow the distribution of this project outside the CurseForge-Overwolf ecosystem"

see https://support.curseforge.com/en/support/solutions/articles/9000207877-project-distribution-toggle

I don't know if there is a way to directly view the state of this setting on projects, other than trying to download it via the api.

**Comment by Eskaan** [comment]
External issue, see above
