### ISSUE TITLE
Installing new Forge modpacks hangs

### ISSUE THREAD

**Issue by Noxally** [killpowa/Twickt-Launcher#1305]
Attempting to dowload and install pretty much any forge modpack hangs either at Downloading Game Files 99% or Downloading Mods 2%.

Example: can download and play Another Quality Modpack 2 (Fabric) but stuck downloading Another Quality Modpack 3 (Forge)

It 100% isnt my network, and if it were firewall related one would expect no downloads to go though, not just some.

**Comment by Eskaan** [comment]
Most likely a Duplicate of #1154
