### ISSUE TITLE
Microsoft Login information & Java settings not retained after app restart

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1310]
**Describe the bug**
1. Microsoft Login Information is not retained after app restart.
2. Java settings are not retained after app restart.

**To Reproduce**
1. Install GDLauncher from inbuild App Market (Discover). Information listed on Discover:
```
Category: Games
Version: 1.1.20, released on 22/12/2021
Author: GorillaDevs
Size: 403.1 MiB on disk
Source: flathub (Flatpak)
Licence: GPL-3.0
Get involved: !Visit the app's website(https://gdevs.io/)
```
2. Open GDLauncher and sign in via Microsoft login.
3. Click on automatic install of Java when prompted.
4. Skip through the tutorial information screen (for the 50th time)
5. Change the General settings - such as the file location; as well as Java settings accordingly - such as the allocated RAM.
6. Restart the application (close and open again fully).
7. Prompt to sign in is shown again.
8. Sign in via Microsoft login.
9. Repeat Step 3 - Click on automatic install of Java when prompted.
10. Repeat Step 4 - Skip through the tutorial information screen (for the 51st time)
11. General settings have been retained; Java settings such as RAM have been reset to default.
12. Closing the app and opening again will result in a loop of steps 2, 4 and 5.

**Expected behavior**
After logging in once, I would expect the login screen not to appear any more. Alternatively at least I would expect a "Do not sign out" or "Keep signed in" button to be visible somewhere on screen - but nothing is present.

**Possible solutions**
I could possibly try and use the file located on the official website - which looks to be an AppImage installer and should be compatible with this distro of Linux.

**Screenshots**
![image](https://user-images.githubusercontent.com/47798787/163894240-518fb4e1-444c-4df0-b1e2-c64410e88f17.png)
![image](https://user-images.githubusercontent.com/47798787/163895056-ff228cb6-a81e-4acc-9571-73e984d9b816.png)

**Operating System:**
- OS: KDE neon User - 5.24 x86_64 
- Version: 1.1.20 (In the app under the settings, it claims the version is 1.1.21)
- Java Version: No Java present on operating-system. (Java installed on container where GDLauncher runs)
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
Originally the launcher also prompted to install Java 9 and Java 17 after the first login and second login. However, after the third login it has stopped appearing.

**Comment by Eskaan** [comment]
Fixed in v1.1.28

**Comment by J-eremy** [comment]
> Fixed in v1.1.28

Nope sure wasn't lol.

New install of 1.1.29 on Windows 11 with launcher provided java and almost every time I open it I have to log back in.

**Comment by Eskaan** [comment]
You may have an issue with the permissions on the AppData folder or connectivity issues. The original issue of all data resetting is fixed.

**Comment by J-eremy** [comment]
> You may have an issue with the permissions on the AppData folder or connectivity issues. The original issue of all data resetting is fixed.

I monitored all traffic in and out from the launcher and Java and no connection issues, Appdata is owned by me with full permissions. I will check in fedora and see how it works there. It logs in successfully, I can play and all that. The issue is when I close it and reopen it I'm logged out and have to log in all over again. I'll try in Linux and a couple other windows systems and if there is a problem I'll open a new issue.

**Comment by MaxLevs** [comment]
> I monitored all traffic in and out from the launcher and Java and no connection issues, Appdata is owned by me with full permissions. I will check in fedora and see how it works there. It logs in successfully, I can play and all that. The issue is when I close it and reopen it I'm logged out and have to log in all over again. I'll try in Linux and a couple other windows systems and if there is a problem I'll open a new issue.

The same issue here. Internet connection is fine. I can one realtime streaming without bufferization and it works. But authorization fails when I open the launcher.
