### ISSUE TITLE
"Open Folder" on instance not working

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1311]
**Describe the bug**
"Open Folder" on instance not working

**To Reproduce**
1. Open GDLauncher.
2. Install at least one instance of Minecraft.
3. Right click the instance and click `Open Folder`

**Expected behavior**
I expected the folder of the instance to open - instead nothing opened.

**Possible solutions**
I could try changing the File Explorer I use - however this would be a big expectation since I would have to reconfigure everything on my system and get used to the new File Explorer, and this might not even solve the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/47798787/163895056-ff228cb6-a81e-4acc-9571-73e984d9b816.png)
![image](https://user-images.githubusercontent.com/47798787/163897175-0de0dbba-bb02-4692-b0de-28e0cc1ad961.png)

**Operating System:**
- OS: KDE neon User - 5.24 x86_64
- Version: 1.1.20 (In the app under the settings, it claims the version is 1.1.21)
- Java Version: No Java present on operating-system. (Java installed on container where GDLauncher runs)
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
System uses Dolphin as File Explorer.

**Comment by ghost** [comment]
I've been having the same issue
Linux Manjaro KDE

**Comment by TDuffinNTU** [comment]
Nevermind, looks like the launcher is abandoned(?) Can't seem to find any active development on it since January.

**Comment by TDuffinNTU** [comment]
@ayden-russo @Supermarcel10 

https://github.com/microsoft/vscode/issues/114425#issuecomment-1736317696

Potential fix below

***

If you have VSCode installed:

1. Remove Snap versions, install the Deb version instead (or other non-sandboxed version for your given distro)
2. modify your `/usr/share/applications/mimeinfo.cache` file by placing `code.desktop;` on the end of the line beginning with `inode/directory`
3. save the file

Should now work immediately.

**Comment by Supermarcel10** [comment]
Closing stale issue. For those that don't know - GDLauncher is out of support. Use [GDLauncher-Carbon](https://github.com/gorilla-devs/GDLauncher-Carbon) instead.
