### ISSUE TITLE
Crashes during jar slide in

### ISSUE THREAD

**Issue by cancel-cloud** [killpowa/Twickt-Launcher#1321]
**Describe the bug**

**To Reproduce**
1. Go to 'Manage -> mods'
3. Slide jar into window
4. See error: 
![image](https://user-images.githubusercontent.com/76657167/166118494-b8a509ac-d46c-4681-9cf0-aed537a9b572.png)

**Expected behavior**
Import jar to instance

**Possible solutions**
im not sure

**Screenshots**
![image](https://user-images.githubusercontent.com/76657167/166118502-5f404d52-00a7-4170-9798-71cbb8d0b08a.png)

**Operating System:**
- OS: Windows
- Version: 11]
- Java Version: 8
- Minecraft Version: 1.8.9
- Mod Loader: Forge
- GDLauncher branch: development / beta

**Comment by Eskaan** [comment]
Still an issue in v1.1.23?
