### ISSUE TITLE
Workaround request: Download mods that are delisted from CurseForge

### ISSUE THREAD

**Issue by commandhat** [killpowa/Twickt-Launcher#1330]
**Is your feature request related to a problem? Please describe.**

When GDLauncher attempts to download a mod that CurseForge has de-listed, the mod in question is silently skipped with no warning or notification.

CurseForge currently de-lists mods if they meet one of the following requirements:
* No files uploaded to the project page
* No files uploaded in 'Release' or 'Beta' status
* No files uploaded less then two years ago

Uploading a new file or mod version supposedly re-lists the mod in question.

This is a 'root issue' that related bugs should be marked as dupe for. Please note that not all bug reports that sound similar may be the same problem, e.g. some mods may intentionally forbid API downloads in their control panel.

**Describe the solution you'd like**
If GDlauncher encounters a mod entry that is not listed, attempt to download the most recent entry for the given mod (since on the CurseForge website, the project sub-page `/download` contains a hyperlink to the most recent version of the mod even if it's delisted). Maybe pop up a warning box telling the user about these unlisted mods? Wording such that 'These mods appear to be abandoned or in early alpha status, as such, expect issues surrounding these: '
Current behavior is to skip the mod upon receiving a 404 for the requested file, which appears to be intentional (irritating) behavior set in place on CurseForge's end.

**Describe alternatives you've considered**

Pop up an error box about certain mods being unlisted and offer a link to their CurseForge page, in case there's an error in the modpack configuration.

Allow retrying of certain downloads such that unlisted mods could reappear later.

Allow the creation of CurseForge cookies that can be used to pretend to login as a user and download. Supposedly this fixes unlisted mod API downloads.

**Additional context**
Various reports have been posted about this issue already, additional data can be collected from them:
#1223 
#1272 (closed)
#1274 
#1278
#1299
#1313 (closed)
#1323 (closed)

**Comment by commandhat** [comment]
API problem worked around, delisted mods now work on the newest version of GDLauncher (download manually, you can't auto-update unfortunately).

**Comment by commandhat** [comment]
@Eskaan Quick notification. THis report has bugs you can close that all relate to the same issue.
Edit: Updated bug list with which bugs were closed before this comment was made.

**Comment by Eskaan** [comment]
Yeah GDL still tries to download the mods, getting a url is null and is then erroring out. Thanks for finding these issues.
