### ISSUE TITLE
GDLauncher Beta - CurseForge not working

### ISSUE THREAD

**Issue by PhweeDev** [killpowa/Twickt-Launcher#1331]
Hello,

Just a few days ago, GDLauncher seems to have completely died on me. I cannot add any mods as it always gives me the "Error loading mod list" (1st image) then it will not Check for Updates. It will, but it doesn't show any required updates (even though there are) and will not load a mod when I click on it. Third, when I add more mods via going to the mods folder, The number does not update. (See second and third image)

![image](https://user-images.githubusercontent.com/44146422/167633570-e00a8b2d-9d91-4d28-9a85-f509ab55e33b.png)

![image](https://user-images.githubusercontent.com/44146422/167633486-b7ea0819-350e-4010-8fff-fa5fa25d8ee1.png)

![image](https://user-images.githubusercontent.com/44146422/167633657-355c2004-c248-4667-b6c3-26323715205f.png)

**Comment by PhweeDev** [comment]
Should mention, I'm using GD v1.1.22-beta.1 with a 1.16.5 and forge 36.2.35 instance.

**Comment by FROMCITRUS** [comment]
API requests through https://api.gdlauncher.com/cf/ are currently failing. This issue only affects Curseforge content. I don't have any way to delve deeper into it myself, but the GDLauncher discord server keeps tabs on the status of this. It is likely just a temporary issue.

**Comment by blarfoon** [comment]
CurseForge banned all proxies for their new APIs (which the beta uses). You can switch to the stable version which should work fine for now.

**Comment by SkeleBones** [comment]
The stable version no longer seems to work now as well.

**Comment by Eskaan** [comment]
Fixed in v1.1.23 f5e7a253bbfa5bfc6674c30c56a42862da6d399e
