### ISSUE TITLE
1.7.10 modpack missing some mods

### ISSUE THREAD

**Issue by TakenNameh** [killpowa/Twickt-Launcher#1332]
**Describe the bug**
1.7.10 modpack "Questing Mayhem" missing some mods. This is not "Questing Mayhem"'s fault because I had manually searched for the missing mods but they didn't show up on the launcher's mod browser. I think it's because if you search for it in the CurseForge site you get "This project is abandoned and its default file will likely not work with the most recent version of Minecraft. Whether this project is out of date or its author has marked it as abandoned, this project is no longer maintained." next to it. One of the mods missing is the mod "Simply Jetpack", the original one. Also, other launchers seem to have no problem whatsoever with the pack.

**To Reproduce**
1. Install "Questing Mayhem"
2. Search for the missing mod. (One of whom as I mentioned earlier is "Simply Jetpack"

**Comment by Jerome226** [comment]
This is because the mods in the pack are in a abandonned state, this is due to a curseforge api change and likely not possible to fix on GDLauncher end.

**Comment by TakenNameh** [comment]
> This is because the mods in the pack are in a abandonned state, this is due to a curseforge api change and likely not possible to fix on GDLauncher end.

Shame. Thanks for clarifying that up!
