### ISSUE TITLE
Curseforge api says error 403 forbidden when trying to load the mods list

### ISSUE THREAD

**Issue by ghost** [killpowa/Twickt-Launcher#1339]
When you try to go to the mods list, it says an error occured. in the dev console it says "403 forbidden" when trying to fetch the curseforge api

1. Go to the mods in your instance.
2. Click on "add mods"
3. you will see that it says an error occured. inside the console it will say 403 forbidden. other errors say 400.

Expected behavior:
the mods list should show up with no issues whatsoever.

Screenshots:
![image](https://user-images.githubusercontent.com/103547259/169142091-8e079214-7387-4971-9903-a12af1035ccc.png)
![image](https://user-images.githubusercontent.com/103547259/169142343-ea55ffc1-5211-4996-b632-a47c4eb7d9a5.png)
![image](https://user-images.githubusercontent.com/103547259/169142399-08f31d55-ec73-4b7c-90da-fb2ed2a38503.png)

Operating System:
- OS: Windows. my Mac is working perfectly fine. they are also both on the same internet.
- Version: 1.1.21
- Java Version: All
- Minecraft Version: All
- Mod Loader: All.

**Comment by commandhat** [comment]
Latest version is v1.1.23:
![image](https://user-images.githubusercontent.com/3821018/169194098-dab1f8cb-6e2f-46db-a635-fece82448bbb.png)

Redownload from the [official website](https://gdevs.io/#downloadContainer) and report back if you're still experiencing this issue.

**Comment by Hedwig7s** [comment]
> Latest version is v1.1.23: ![image](https://user-images.githubusercontent.com/3821018/169194098-dab1f8cb-6e2f-46db-a635-fece82448bbb.png)
> 
> Redownload from the [official website](https://gdevs.io/#downloadContainer) and report back if you're still experiencing this issue.

Am on .23
Can confirm it works on .23 (although the curseforge icon on the mods is missing)

**Comment by Eskaan** [comment]
Yeah the old Curseforge API was shut down so versions below v1.1.23 wont longer work.
Fixed in f5e7a253bbfa5bfc6674c30c56a42862da6d399e

**Comment by ghost** [comment]
thank you! i reinstalled it and it works perfectly!
