### ISSUE TITLE
Cannot seem to connet to Curseforge

### ISSUE THREAD

**Issue by alorg** [killpowa/Twickt-Launcher#1340]
I have not been able to update any of the mods I have on any instances, able to add any other mods or modpacks. It seems that GDLauncher is not connecting to curseforge at all.
This has been occurring in the past 2 days I believe.

**Comment by alorg** [comment]
Ignore. Updated to latest version and noticed message, so I know you are aware of curseforge API issues...

**Comment by burtek** [comment]
Last version works tho, so try again ;)
