### ISSUE TITLE
Potential API key leak.

### ISSUE THREAD

**Issue by Unnoen** [killpowa/Twickt-Launcher#1344]
The latest commit https://github.com/gorilla-devs/GDLauncher/commit/371559a548a391ff50fa354e055530952acb8644 exposes an API key.
https://github.com/gorilla-devs/GDLauncher/blob/371559a548a391ff50fa354e055530952acb8644/src/common/api.js#L23

I'm not sure if this is intended or not. If it is (such as a public key), I suggest putting a comment above it describing it as such, as right now it looks like an unintentional leak.

I also recommend setting up a [security policy on GitHub](https://github.com/gorilla-devs/GDLauncher/security) so potential issues like this can be disclosed privately.

**Comment by Eskaan** [comment]
Intended, you can get it from the sections easily anyways.
Thanks for reporting tho.
