### ISSUE TITLE
Forge instance keeps trying to download a quilt version of a mod

### ISSUE THREAD

**Issue by BugmanBugman** [killpowa/Twickt-Launcher#1347]
**Describe the bug**
Title. My GDlauncher instance keeps trying to download the quilt instance of geckolib for some reaon 
**To Reproduce**

1. make a forge 1.18.2 instance
2. download geckolib
3. notice that it defaults to quilt for some reaosn

**Expected behavior**
to not download quilt

**Screenshots**
![image](https://user-images.githubusercontent.com/40730042/171228126-f33fe527-bdf9-4b2c-bf9c-7f0de798745a.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 16
- Minecraft Version: [1.18.2]
- Mod Loader: Forge
**Additional context**

**Comment by rdellison** [comment]
It also shows GeckoLib with update available after manually selecting the forge version

**Comment by Eskaan** [comment]
Yeah, that is a common issue with CF that mods are marked with multiple loaders. We can't do anything about it, ask the mod authors to fix it by making them multiple projects (they should be multiple sources anyways)
