### ISSUE TITLE
CurseForge tab not functioning

### ISSUE THREAD

**Issue by JHCode-Python** [killpowa/Twickt-Launcher#1349]
**Describe the bug**
When clicking on the curseforge tab of the instance browser, all the shows is "An error occurred while loading
the modpacks list", and a png of a cartoon bomb.

**To Reproduce**
1. Go to 'Add new instance'
2. Click on 'CurseForge'

**Expected behavior**
When clicking on curseforge, I expect to to see the curseforge modlists

**Possible solutions**
I haven't a clue, but ive heard talk of the curseforge API changing, so that might have something to do with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/105920468/171469342-575d71fd-d7d2-46e2-8dd2-2c6ec3492a9f.png)

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: CurseForge

**Additional context**
N/A

**Comment by SubnormalGamer** [comment]
this happens but when i try to open the add mods page on my fabric instance

**Comment by Eskaan** [comment]
You are not on the latest dev build I think? If yes that's a duplicate with another Symptome of #1342

**Comment by JHCode-Python** [comment]
i am not sure how to enable dev builds, but i am on version 1.1.21. it says "up to date" at the bottom

**Comment by Eskaan** [comment]
Yeah. There is a dev build where it's fixed, we are just waiting for the release.
