### ISSUE TITLE
Can't load new instance from zip file

### ISSUE THREAD

**Issue by JHCode-Python** [killpowa/Twickt-Launcher#1350]
**Describe the bug**
When clicking on "Import Zip" and selecting a file, I get stuck in a loop of loading, having lasted at minimum of 3 hours before I gave up.

**To Reproduce**
1. Go to 'Add New Instance'
2. Click on 'Import Zip'
3. Click on (valid zip file- project ozone 3 in my case)
4. Add name "PO3"
5. Click the arrow to continue
6. See error

**Expected behavior**
I would expect the zip to be added to the instance folder rather quickly, as it is already downloaded, and unzipping doesn't take too long.

**Possible solutions**
Perhaps just a copy and paste of the zip folder into the instance folder, then unpack and delete the old zip folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/105920468/171470490-16818713-0f0e-47a7-bb15-85931ec24583.png)
![image](https://user-images.githubusercontent.com/105920468/171470523-cd517e28-2993-4a2a-999b-e7bd2a7990b7.png)
![image](https://user-images.githubusercontent.com/105920468/171470547-c2e66f78-e200-4804-93a7-c15df5ef6b00.png)

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: Not sure
- Minecraft Version: 1.12.2
- Mod Loader: Originally downloaded from CurseForge app because of previously submitted issue,

**Additional context**
I started the Add Instance process, got up to do a thing, got sidetracked, came back 3 or more hours later to see no difference.
It took a minute and a half to download the file, and another 15 seconds to compress it, it doesnt take 3 hours to uncompress a file of this miniscule size.

**Comment by Eskaan** [comment]
Could you show us the console (>_ at the top) after the failed import?
You mean you exported an already downloaded instance from the CF App right?
If you want to, in the latest dev build the issue is already fixed and currently being tested.

**Comment by JHCode-Python** [comment]
I will have to check the console while I’m at my office tomorrow, and yes, the instance was already downloaded from the CF app and was on my desktop.

**Comment by JHCode-Python** [comment]
![image](https://user-images.githubusercontent.com/105920468/171964214-1ca1235f-81f3-4870-b458-39c4d5cf6405.png)

Here is the console after a failed export, i only waited about 5 minutes this time, but this is what the entire log consisted of.

**Comment by Eskaan** [comment]
Yeah, that's the new API problem. Yet andother symptom of #1342

**Comment by EliGames2267** [comment]
The same thing happens to me
