### ISSUE TITLE
Add legacy fabric to the version chooser (legacyfabric.net)

### ISSUE THREAD

**Issue by Kokonico** [killpowa/Twickt-Launcher#1354]
**Is your feature request related to a problem? Please describe.**
A major issue on my mac is that forge does not work on it (this is not a GDlauncher issue, i checked.)

**Describe the solution you'd like**
I would appreciate it if there was an extra tab in the fabric menu called "legacy" that would have the legacy versions of fabric so I can run mods on older versions using my mac due to it's inability to run forge.

**Describe alternatives you've considered**
I have looked everywhere and tried everything but i can't find any alternatives. 

**Additional context**
concept art I made:
<img width="879" alt="fabriclegacy" src="https://user-images.githubusercontent.com/96935064/172910618-0039e876-20a0-44d5-baa8-405d886156d8.png">

legacy fabric website: legacyfabric.net

**Comment by Eskaan** [comment]
I don't think this project has any kind of public API we could use to make it work in GDL, also there is no documentation for it.
