### ISSUE TITLE
`Update all mods` button is being really weird

### ISSUE THREAD

**Issue by srnyx** [killpowa/Twickt-Launcher#1369]
**Describe the bug**
The `Update all mods` button acts really strange when clicking `Check for updates` and then the 3 dots button to the right of it.

**To Reproduce**
It's pretty random to be honest but this is usually what I do:
1. Manage instance
2. Go to mods
3. Click `Check for updates`
4. Click the 3 dots to access the `Update all mods` button, sometimes it'll do something weird, sometimes it'll work normally

You may have to close out of the instance manager and then repeat the steps to actually get it to bug.

**Screenshots**
https://media.srnyx.xyz/updatemods.mp4

**Operating System:**
- OS: Windows 10
- Version: 1.1.24
- Java Version: GraalVM 17

**Comment by Ladvace** [comment]
let me know if this fix: https://github.com/gorilla-devs/GDLauncher/pull/1381
