### ISSUE TITLE
Open mod page button doesn't work

### ISSUE THREAD

**Issue by srnyx** [killpowa/Twickt-Launcher#1373]
**Describe the bug**
Nothing happens when you click the "open mod page" button when viewing a mod.

**To Reproduce**
1. Click on a CurseForge mod in your instance's mod list
2. In the top left, click the link button to open the mod's CurseForge page
3. Nothing happens

**Expected behavior**
It should open a web tab/window of the mod's CurseForge page.

**Screenshots**
![](https://media.srnyx.xyz/r/page.gif)

**Operating System:**
- OS: Windows 10
- Version: 1.1.25
- Java Version: GraalVM 17

**Comment by Eatham532** [comment]
Can confirm this is true

**Comment by Yoosk** [comment]
Same here, doesn't work

**Comment by Eskaan** [comment]
Logs / Console please

**Comment by Yoosk** [comment]
Above commit seems to fix it properly, you can check with the dev build. https://nightly.link/gorilla-devs/GDLauncher/actions/runs/2520100203

**Comment by srnyx** [comment]
> Logs / Console please

Nothing appears in console

**Comment by Ladvace** [comment]
I just opened a pr to fix this
