### ISSUE TITLE
Unable to start Forge 1.19

### ISSUE THREAD

**Issue by Fede2782** [killpowa/Twickt-Launcher#1379]
**Describe the bug**
After creating an instance with Forge 1.19, I tried to start that instance but it didn't start. It made error "Error: Uncaught Fatal Exception Code: 1". There was also the error "Command line too long" under. I've tried this with Forge 41.0.45.

Sorry for my English.

**To Reproduce**
1. Create a clean instance with Forge 1.19 
2. Click on Play
3. See error

**Expected behavior**
Instance start

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 16
- Minecraft Version: 1.19
- Mod Loader: Forge

**Comment by DeciTM** [comment]
https://github.com/gorilla-devs/GDLauncher/issues/1359
