### ISSUE TITLE
Parts of the pop-up windows render when the main window is smaller than normal

### ISSUE THREAD

**Issue by Dazaisan99** [killpowa/Twickt-Launcher#1386]
**Describe the bug**
Certain windows, such as the settings menu or the "manage instance" menu, don't adapt to the size of the window when opened, thus hiding some parts of the window : buttons, text and so on.

**To Reproduce**
1. Right-Click on an instance
    Click on "Manage"
OR go into the settings menu
2. Resize the window in such a way so that the window is about 800px wide ( works for me, but the width of the window necessary to make it bug probably depends on the size of your monitor, I'm sorry I couldn't be more precise on this )
3. See error : some of the buttons are missing, text is hidden, info boxes disappear, etc.

**Expected behavior**
The window should have adapted to the window resolution

**Screenshots**
Settings menu : 
![2022-06-28-162850_770x787_scrot](https://user-images.githubusercontent.com/96884464/176210458-eebb905e-63f2-4d42-8269-d959c8162cdd.png)

Instance manager : 
![2022-06-28-162025_653x636_scrot](https://user-images.githubusercontent.com/96884464/176210616-d43ac571-190c-4cda-a62d-366baae78df1.png)
 In an even smaller window : 
![2022-06-28-161929_426x633_scrot](https://user-images.githubusercontent.com/96884464/176210716-28a43966-3738-464d-98f0-7b6737c1df14.png)

**Operating System:**
- OS: Arch Linux
- Version: GDLauncher v1.1.25
- Java Version: Java 17
- Window manager: i3gaps

**Comment by Eskaan** [comment]
Same issue with Awesome. The problem is that the wm ignores the set minimum window size parameters. See https://github.com/gorilla-devs/GDLauncher/blob/316b0b4342476801e76dfc4e3b83de94bc297860/public/electron.js#L263-L264
Either electron ow wm issue
