### ISSUE TITLE
Launcher will not initiate instance

### ISSUE THREAD

**Issue by Frylock221** [killpowa/Twickt-Launcher#1389]
When I open any instance, the launcher will open and load all of the files, but hangs on "loading-completing minecraft initialization". It will not start the game
![20220630_114254](https://user-images.githubusercontent.com/108488775/176754083-42f4ffd4-24c6-4f83-8f1c-cea42f4e93a9.jpg)

**To Reproduce**
1. Open GDLauncher
2. Select instance to load
3. Wait for all modpack info to load
4. stuck on completing initialization

**Expected behavior**
Starting the game after loading

**Operating System:**
- OS: Windows 11 pro
- Version: 21h2
- Java Version: 
- Minecraft Version: 1.12.2
- Mod Loader: FTB 

**Additional context**

**Comment by Eskaan** [comment]
Are there any errors in the GDL Console when downloading/launching a pack? Otherwise this is a Modpack issue.
