### ISSUE TITLE
Error on CourseForge Requests

### ISSUE THREAD

**Issue by FrancoCab10** [killpowa/Twickt-Launcher#1390]
**Describe the bug**
CourseForge not working on my launcher.

**To Reproduce**
1. Go to 'Add New Instance'
2. Click on the 'CourseForge' tab
3. Error happens.

Also:
1. Right-click on an Instace
2. Click on the 'Manage' menu item
3. Click on the 'Mods' menu item
4. Click on the 'Add Mods' button
5. Error happens.

**Expected behavior**
Should load modpack & mod list

**Possible solutions**
'Network' tab on devtools shows a 400 error so should be easy to solve with some CourseForge request change.

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 16
- Minecraft Version: Any
- Mod Loader: Any

**Screenshots**
![image](https://user-images.githubusercontent.com/46230292/177076636-7598a3ed-1537-4d53-bc7d-a1500b3b2f6e.png)
![image](https://user-images.githubusercontent.com/46230292/177076711-353aa960-2b2a-4591-81a5-9fee37dce2be.png)
![image](https://user-images.githubusercontent.com/46230292/177077020-723b5ba1-91c8-4df2-93a5-ae12a7186008.png)

**Comment by Eskaan** [comment]
Are you on the latest version? (v1.1.25)

**Comment by FrancoCab10** [comment]
I am, yes. But I fixed it a moment ago.

First tried reinstalling the launcher without deleting files and it was still happening.
After deleting all files and then reinstalling it got fixed.

Maybe a corrupted file or instance? I just saved some worlds and they loaded fine.

Do I close the issue?
