### ISSUE TITLE
Feature: pretty format config.json

### ISSUE THREAD

**Issue by Flachdachs** [killpowa/Twickt-Launcher#1392]
**Is your feature request related to a problem? Please describe.**
When you maintain a modpack and want to have these changes documented in a VCS like Git the current format of the config.json is not very useful, because it is a single long line. And Diff tools compare line by line.

**Describe the solution you'd like**
Please create the config.json in pretty format. Such an option is usually included in the stringify functionality. Additionally the order of mods should be stable, so that the Diff only sees real differences apart from the order. A simple sort by modID should be fine.

**Comment by Ladvace** [comment]
we don't format it on purpose, in order to make the config lightweight, if you really need to have a readable format you could use the format functionality of vscode / whatever editor/ide you use.
