### ISSUE TITLE
Unable to join online servers/reams due to "invalid session id" dispite relogging and reinstalling

### ISSUE THREAD

**Issue by Kokonico** [killpowa/Twickt-Launcher#1401]
**Describe the bug**
Note: i am not the one experiencing this bug, it is my friend as he can't make a github account.
for some reason my freind gets a invalid session error whenever using gdlauncher while trying to connect to a server. (i know it says restart your launcher, but he did that and he even reinstalled and relogged in)
**To Reproduce**
unfortunately i do not know how to reproduce the error.

**Expected behavior**
join server with no issues whatsoever

**Possible solutions**
what if you checked for a session id right before you launch your game and if you didn't have one it would generate a new one?

**Screenshots**
N/A

**Operating System:**
- OS: Windows
- Version: 1.1.25
- Java Version: all
- Minecraft Version: 1.19 and 1.18 are the only confirmed versions. it should affect others as well.
- Mod Loader: all

**Additional context**
my freind has relogged, reinstalled, repaired instances, and done everything.

**Comment by Eskaan** [comment]
You're on a old Mojang account. These are officially deprecated and have been banned from online play recently. You have to migrate your account to continue to play online.
