### ISSUE TITLE
Download Freezes when downloading from FTB and no url is available for mods

### ISSUE THREAD

**Issue by bfrizbee** [killpowa/Twickt-Launcher#1405]
**Describe the bug**
Download gets stuck when downloading FTB files for FTB modpack. I am trying to download FTB Oceanblock

**To Reproduce**
1. Download modpack from FTB - For example FTB OceanBlock
2. Download/install freezes while downloading FTB files

**Expected behavior**
Download should finish and instance should be playable

**Possible solutions**
I looked at the console and it appears to be skipping many mods, due to not having a direct URL, but rather curseForge information. My guess is when downloading a modpack not directly from curseforge, it expects the url to always be there, and if not just returns. It doesn't bother checking if it is available on curseforge or attempting to download with the given information.

**Screenshots**
![image](https://user-images.githubusercontent.com/13514862/180623732-7a7725d5-362e-4e93-b388-82d22e3a7e4d.png)

![image](https://user-images.githubusercontent.com/13514862/180623783-07078310-b37a-40f3-b5be-6bca1dd79fa4.png)

![image](https://user-images.githubusercontent.com/13514862/180623803-470709d7-8627-42c9-92db-9a839fc1d281.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 8/17 both installed
- Minecraft Version: Modpack I'm trying to download is 1.16.5
- Mod Loader: Forge

**Additional context**
After closing and re-opening the launcher, the instance looks like it is finished. It can be started but will error out saying it is missing mods

**Comment by bfrizbee** [comment]
I had downloaded the src and added a little hack to it to download the files available through curseforge api, but then I ran into issue with the ones that would require the browser download and I couldn't get that working. Was hoping a little hack would get it going ;).

**Comment by Eskaan** [comment]
Wow. Your Autoupdater was fast. Yeah Davide directly saw that too and is working on it atm.

**Comment by TemperingPick** [comment]
Any update on this bug? It's affecting almost every FTB modpack. Happy to contribute if someone can point me in the right direction.

**Comment by Eskaan** [comment]
I think Davide fixed it in 1.1.27?

**Comment by TemperingPick** [comment]
Cheers, looks fixed from here. Thanks!
