### ISSUE TITLE
Add support for Modrinth

### ISSUE THREAD

**Issue by SnowedInOwl** [killpowa/Twickt-Launcher#1407]
**Is your feature request related to a problem? Please describe.**
Add support for Modrinth. 
(I Don't think there really other way to explain this but if this isn't good Enough in any way Please let me know.)

**Describe the solution you'd like**
Add support for Modrinth
(I Don't think there really other way to explain this but if this isn't good Enough in any way Please let me know.)

**Describe alternatives you've considered**
None

**Additional context**
[Modrinth](https://modrinth.com/)

**Comment by Eskaan** [comment]
Duplicate of #768
