### ISSUE TITLE
Minecraft Client is Killed when exiting the launcher

### ISSUE THREAD

**Issue by SirOMGitsYOU** [killpowa/Twickt-Launcher#1415]
**Describe the bug**
Minecraft Client is Killed when exiting the launcher once you have a game launched if you x out of the launcher it kills any game clients attached

**To Reproduce**
1. Launch GDL
2. Launch a profile
3. Close GDL using the X 
4. Client process gets killed and GDL Closes

**Expected behavior**
GDL To close on it's own leaving the client detached and doing its own thing

**Possible solutions**
Fix whatever is killing the client on launcher close

**Operating System:**
- OS: [e.g. Windows] Windows 
- Version: 11
- Java Version: [e.g. 8/16] 16
- Minecraft Version: [e.g. 1.16.5] 1.16.5
- Mod Loader: [e.g. Forge/Fabric] Forge

**Additional context**
If this was added as a feature pls revert this is not an ideal feature in any world :D

**Comment by Ladvace** [comment]
I fixed this bug here https://github.com/gorilla-devs/GDLauncher/pull/1412
