### ISSUE TITLE
[Suggestion/Bug] Exclude mods for the improper mod loader in the mods list & GDLauncher sometimes adds wrong versions of mods

### ISSUE THREAD

**Issue by Nevrai** [killpowa/Twickt-Launcher#1423]
When looking or searching for mods in the mods list, after clicking ‘Add Mods’ when managing an instance, it shows Fabric mods despite the instance using Forge—and would presumably also show Forge mods when the instance uses Fabric or Quilt (although I haven’t tested that).

Additionally, when adding a mod that has a dependency, GDLauncher will sometimes add the Fabric or Quilt version of that dependency, which happened to me on numerous occasions, one of which when I added [Consistency+](https://www.curseforge.com/minecraft/mc-mods/consistencyplus) and GDLauncher added the Fabric version of its dependency, [Stonecutter Recipe Tags](https://www.curseforge.com/minecraft/mc-mods/stonecutter-recipe-tags). Another time, it added the Quilt version of [Excavated Variants](https://www.curseforge.com/minecraft/mc-mods/excavated-variants) instead of the Forge version. So that part could probably be considered a bug.

My suggestion is to add a built-in filter to the launcher that excludes mods for the improper mod launcher in the mods list (without excluding mods that have separate versions for both Forge and Fabric or versions that support both mod loaders at the same time). Essentially, it’d just look at the mod loader tags on the CurseForge files to see if the tag corresponds with the mod loader your instance uses (and I suppose just include it in the list if it has no tag, since it wouldn’t have any way to know in that case). This is how it works in the CurseForge launcher, and it’d be nice to see it in GDLauncher as well.

#### Versions
* **GDLauncher version:** 1.1.27 (latest stable version)
* **OS:** Windows 11 Home, version 21H2

**Comment by Eskaan** [comment]
Duplicate of #1204

**Comment by Nevrai** [comment]
@Eskaan It’s only partly a duplicate, since my issue also covers the lack of filtering out Fabric mods when using Forge, or vice versa, which CurseForge’s launcher supports. Why is this not planned? Would make downloading mods a lot more convenient.

**Comment by Eskaan** [comment]
The other issue was initially a bug report about Geckolib. It's a bug that affects all Modloaders tho.

I usually mark duplicates as not planned. The alternative would be marking them as completed, which I feel is even more improper.
