### ISSUE TITLE
No SLF4J Providers were found. Code : 1

### ISSUE THREAD

**Issue by eijrin** [killpowa/Twickt-Launcher#1424]
**Describe the bug**
When trying to load Minecraft 1.19 the instance fails to launch and proceeds to show you this message. 
![5DuftdUZ8](https://user-images.githubusercontent.com/73799016/182184619-077e2a21-7595-4eca-849d-35fc97898dad.png)
![5DufI8fSm](https://user-images.githubusercontent.com/73799016/182184767-6eb91931-3f58-42e7-b3e2-de412d33e168.png)

**To Reproduce**
1. Create a Fabric 0.14.8 version of Minecraft 1.19
2. Install the following mods 
![5DufVrYa3](https://user-images.githubusercontent.com/73799016/182184903-9ab4cc96-7a65-4224-a792-9d3c072817d8.png)
3. Try and launch 1.19

**Expected behavior**
The game launches as usual, but instead it throws this exception.

**Possible solutions**
From what I can grasp from the error log tis an issue with optifabric, but I'm really not sure as it works fine when they're disabled. Perhaps this is just an issue with optifabric.

**Operating System:**
- OS: Windows
- Version: 11 2H22 Beta
- Java Version: 17
- Minecraft Version: 1.19
- Mod Loader: Fabric 0.14.8

**Additional context**

**Comment by Ladvace** [comment]
do you have the following error even with a fresh instance without any mods?

**Comment by Eskaan** [comment]
If launching a fresh instance works this is not a GDL issue, but an issue with the Mod that caused the error.

**Comment by T1MOXA** [comment]
I would like to understand what kind of mod. Since there is nothing in the latest log indicating the problem (

**Comment by Furret01** [comment]
The issue is architectury, which does not work well for some reason or another. I tested this on a modpack on my own and got the same issue, and thanks to this post i was able to narrow down the mods causing the issue and solved it. Thanks for making this thread!
