### ISSUE TITLE
instances wont launch

### ISSUE THREAD

**Issue by Fennecai** [killpowa/Twickt-Launcher#1425]
**Describe the bug**
Instances will not start now even though I started one yesterday. (this might be more a support thing than a bug)
![image](https://user-images.githubusercontent.com/10889213/182382196-ab84a686-9b31-43f4-83b1-6bff2330c6b3.png)

**To Reproduce**
1. play an instance
2. guess you arent gonna be playing though
3. look at the console

**Expected behavior**
I wanted it to launch

**Possible solutions**
I have no idea

**Screenshots**
![image](https://user-images.githubusercontent.com/10889213/182382503-3dac5cce-7b2e-4372-abb2-61fa123661ce.png)
![image](https://user-images.githubusercontent.com/10889213/182382635-33db56fc-6ed4-40c5-821d-58b002f241c6.png)

**Operating System:**
- OS: windows
- Version: 10
- Java Version: 
my system says this: 
![image](https://user-images.githubusercontent.com/10889213/182382977-b3c7447a-f2b1-48f2-b3a7-b3c6dc3b3ece.png)

- Minecraft Version: doesn't matter; happens with all instances. instance pictured is 1.17.1
- Mod Loader: doesn't matter, happens with and without forge or fabric. instance pictured uses fabric.

**Additional context**
I just recently re-installed windows and stuff and the java is a bit weird currently I guess

**Comment by Eskaan** [comment]
That usually means you either have to run the automatic java setup again or set the path to your already installed java executable manually.

**Comment by Fennecai** [comment]
ah- that seems to have been the issue, thanks.
