### ISSUE TITLE
1.19.1 Forge and Fabric dont install

### ISSUE THREAD

**Issue by Jaxlyfe** [killpowa/Twickt-Launcher#1426]
(Have not tested with other versions)
When installing 1.19.1 forge or fabric all that is created is a config file from GDlauncher. Nothing else, not even a folder structure.

Note : I can install vanilla perfectly fine

**Comment by Eskaan** [comment]
Are there any errors in the console whilst installing?

**Comment by Jaxlyfe** [comment]
POST http://159.89.252.15:9000/api/1/envelope/?sentry_key=514c376…&sentry_version=7 net::ERR_CONNECTION_TIMED_OUT

**Comment by Eskaan** [comment]
Are you on the latest version (v1.1.27)?
Is that everything that comes up?
It could also be a log message.

**Comment by Jaxlyfe** [comment]
Yes I am on 1.1.27.

It seems to have fixed itself now? 
I am unable to recreate the bug.

**Comment by Ladvace** [comment]
> Yes I am on 1.1.27.
> 
> It seems to have fixed itself now? I am unable to recreate the bug.

have you got the problem again since that?
