### ISSUE TITLE
Launcher ignores width and height

### ISSUE THREAD

**Issue by revdave33** [killpowa/Twickt-Launcher#1427]
**Describe the bug**
I have the configuration options for width and height set to 1920 and 1080 in the java area of the configs (where I've had it and it has worked in the past). I updated to 1.1.27 in order to run 1.19.1 and now when I launch an Instance (any instance) the window is 854x480 (according to F3 debug screen). 

In looking at the console log, there is this line:
actions.js:3268 Completely ignored arguments: [--width 1920, --height 1080]

**Operating System:**
- OS: WIndows
- Version: 10
- Java Version: 17
- Minecraft Version: 1.18.2
- Mod Loader: Forge 40.1.69
- GDLauncher: 1.1.27

**Comment by Ladvace** [comment]
I opened a pr: https://github.com/gorilla-devs/GDLauncher/pull/1429
