### ISSUE TITLE
Editing instance note crashes the launcher

### ISSUE THREAD

**Issue by MustaDevelop** [killpowa/Twickt-Launcher#1434]
**Describe the bug**
The crash happens randomly when I try editing the note

**To Reproduce**
1. Go to the instance manage window
2. Click on note
3. Edit the note(it happens randomly)
4. See crash

**Expected behavior**
I think it happens after I quit the game from the instance and then edit it

**Screenshots**
![GDLauncher_dkHTnaFPvX](https://user-images.githubusercontent.com/77793061/183904185-73ecfbef-1b63-4475-88dc-ca87bfcdac97.png)

**Operating System:**
- OS: Windows
- Version: 10
- Java Version: 17
- Minecraft Version: 1.19.1
- Mod Loader: Fabric

**Comment by Ladvace** [comment]
could you open the console in the top left corner and paste here the error logs?

**Comment by MustaDevelop** [comment]
> could you open the console in the top left corner and paste here the error logs?

I will try that

**Comment by MustaDevelop** [comment]
> > could you open the console in the top left corner and paste here the error logs?
> 
> I will try that

So I tried and wasn't able to find anything
but I found out how it works, when I hold the backspace key(which deletes letters faster than spam pressing) it causes the crash
probably has something to do with the typing and not the instance itself
