### ISSUE TITLE
problem is an error when trying to install forge on version 1.3.2

### ISSUE THREAD

**Issue by Isaich24** [killpowa/Twickt-Launcher#1435]
Hello. I have problems with GDlauncher, can you help me, or advise who to contact for help. The problem is an error when trying to install forge on version 1.3.2.
![image](https://user-images.githubusercontent.com/111115749/184314674-f8eb5ac2-4f20-4f7d-bf9f-210ebb9bb19d.png)
![image](https://user-images.githubusercontent.com/111115749/184314636-73c75d03-1853-415e-b3d7-05cae7e3520f.png)
reinstalling the launcher did not solve the problem, but the text changed:
![Screenshot_1](https://user-images.githubusercontent.com/111115749/184314762-7e8eea89-fa2d-4383-99a8-33703c3e08f0.png)
logs from the console after restarting the launcher and trying to install the version:
![image](https://user-images.githubusercontent.com/111115749/184316916-c780ff6a-f60f-4856-afb8-80198830b445.png)
![image](https://user-images.githubusercontent.com/111115749/184316873-9395103a-eed0-4df3-84b0-9367b13a5484.png)
console after restarting PC and reinstalling launcher:
![image](https://user-images.githubusercontent.com/111115749/184405186-e32f3a54-07dd-4432-ad28-1b14a2b5b38c.png)

**Comment by Isaich24** [comment]
I checked the IP with the connection to which there are problems and realized that the problem is in the country in which I am

**Comment by Ladvace** [comment]
actually I got the same problem
