### ISSUE TITLE
GD Launcher is losing track of my instance data folder after computer restart

### ISSUE THREAD

**Issue by Inglonias** [killpowa/Twickt-Launcher#1457]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_A clear and concise description of what the bug is._

**To Reproduce**
1. Set up GDLauncher on a fresh Win10 computer. Ensure that the computer has a D: drive that you can write to.
2. Download some instances, use as normal.
3. Change the Instance Data directory to a folder on D:
4. Quit the launcher.
5. Reboot the computer.
6. When you restart GDLauncher, it behaves as though it's the first time launching
7. Set the instance data location back to the D: drive.
8. GDLauncher behaves normally
**Expected behavior**
GDLauncher will not lose the instance settings location.

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: Windows 10
- Launcher Version: 1.1.29
- Java Version: 8/17
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
I would be thrilled if this was just a write-permission issue on my end, but I don't know which file it would be if it is.

**Comment by Eskaan** [comment]
You may have to wait some time untill all instances are copied. Could you look out and show us any console errors (>_ at the top)?

**Comment by Inglonias** [comment]
If the bug reoccurs, I'll send the console info

**Comment by Inglonias** [comment]
Closing, since a restart was not able to reproduce the issue.
