### ISSUE TITLE
46 Security Vulnerabilities

### ISSUE THREAD

**Issue by taciturnaxolotl** [killpowa/Twickt-Launcher#1469]
- [ x] I searched the issue tracker for other issues covering my case
- [ x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
npm during build states that their are ```46 vulnerabilities (1 low, 8 moderate, 29 high, 8 critical)```

**To Reproduce**
1. Build Gd Launcher
2. Observe

**Expected behavior**
No vulnerabilities

**Possible solutions**
Update affected packages

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: [arch]
- Launcher Version: [v1.1.29]
- Java Version: [N/A]
- Minecraft Version: [N/A]
- Mod Loader: [N/A]

**Additional context**
_Add any other context about the problem here._
This occurred while building with the aur.

**Comment by Eskaan** [comment]
You can of course try to fix our dependency resolution, but let me tell you: I tried it before, it was basically impossible at that point.
Edit: If you can demonstrate one of those vulnerabilities on the project, that would of course be another thing.

**Comment by taciturnaxolotl** [comment]
That makes sense I figured there was probably a reason for them being left.
