### ISSUE TITLE
Can't login with MS account

### ISSUE THREAD

**Issue by line-0707** [killpowa/Twickt-Launcher#1471]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Can't login with MS account. An error is displayed.

**To Reproduce**
0.The launcher has not created a launch configuration and is not logged in to anything
1. Launch a GDLauncher
2. Sign in with  Microsoft
3. Perform the prescribed action for logging in
3-1.My MS account is set to passwordless account, so I need to log in using MS Authenticator.

**Expected behavior**
An error related to Xbox Live has occurred and I cannot log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/78641260/200102339-bc44a39c-6e11-47aa-a456-d21923d8798b.png)

**Operating System:**
- OS: Windows11
- Launcher Version: 1.1.29
- Java Version: Maybe 8/17　(Java version displayed in current version)
- Minecraft Version: none
- Mod Loader: none

**Additional context**
_Add any other context about the problem here._

**Comment by line-0707** [comment]
Oh my god! I didn't label it!
I'm sorry.

**Comment by Eskaan** [comment]
We have quite a few issues with the Micrsoft login (it's a nightmare for programmers).
The most related ones should be [these](https://github.com/gorilla-devs/GDLauncher/issues?q=is%3Aissue+Xbox+Secure+Token). Reopened #1116 for you.
