### ISSUE TITLE
Uncaught Fatal Exception code: 1

### ISSUE THREAD

**Issue by line-0707** [killpowa/Twickt-Launcher#1476]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
#1458 and #1359 and the errors displayed in the launcher seem to be the same.
The only difference is that the detailed text is clearly displayed instead of "too long" or "exception in thread main".

**To Reproduce**
1. Set up any instance
2. Add mod (If me,46 mods)
3. After completing the above steps, start the instance
4. Minecraft won't start at all and gives an error

*The following procedure will give the same result

0. As a prerequisite, it is in a state where it does not start with the above procedure
1. Export the instance and save it anywhere
2. Press "Create Custom Profile" from Curseforge
3. Select the previously saved instance from "Or import a previously created profile"
4. Start the instance when ready
5. Minecraft will not open, and unlike GDLauncher, there is no error display

**Expected behavior**
It may be caused by one of the mods added towards the end.
Because it was working until I added some mods.

**Possible solutions**
No idea

**Screenshots**
I couldn't fit it all in one piece.
I will attach the detailed message copied from the developer tools instead.
[Error.txt](https://github.com/gorilla-devs/GDLauncher/files/9999402/Error.txt)

**Operating System:**
- OS: Windows 11 Home Insider Preview Installed build: 25236.1010 rs_prerelease.221028-1618
- Launcher Version: V1.1.29
- Java Version: Unknown (version recommended by this launcher)
- Minecraft Version: 1.19
- Mod Loader: Forge

**Additional context**
_Add any other context about the problem here._

**Comment by Eskaan** [comment]
This is not a launcher issue, but an issue with one of the mods you added. After reading the error logs, I would recommend looking at `puzzleslib`.
