### ISSUE TITLE
Extremely slow download.

### ISSUE THREAD

**Issue by Kame03** [killpowa/Twickt-Launcher#1478]
I have 150/20 Mb/ps download speed, and it takes me more than 20 minutes to import a .zip file or create a new instance because it takes so long to download, while other launchers including the official Minecraft launcher take less than a minute or a couple of minutes at least. 

This is what the console shows:
![image](https://user-images.githubusercontent.com/98698826/202240243-b880b16f-4e44-4123-be2d-7b7361778224.png)

And the download fails at the end.
![image](https://user-images.githubusercontent.com/98698826/202240426-fc9950cb-c5db-402f-a7b2-233eae221947.png)

After retrying the download it succeeds as it continues from where it failed at about 90%, but after that time I lost a lot of minutes waiting. 

Here's the log: https://justpaste.it/4fz8s

Issue #1115 already exists but I feel like it didn't receive enough deserved attention for this to be fixed so I'm creating this one instead, it can later be merged if needed.

**Comment by Eskaan** [comment]
It's still a duplicate. You should have commented that you are having this error with your error logs over there to bump the issue.
Thanks for searching and writing a report tho. :)
