### ISSUE TITLE
Logging in through MS account results with error 429

### ISSUE THREAD

**Issue by Thedoczek** [killpowa/Twickt-Launcher#1479]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
I can't log in with Microsoft account. After entering credentials, I am kicked back to login screen with error

**To Reproduce**
1. Log in with Microsoft account (it kicked me to login screen even though I was logged in before)
2. Error

**Expected behavior**
Guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/69758777/202866226-9c75ad7e-2176-46a6-a84b-85568fd24b95.png)

**Operating System:**
- OS: w11
- Launcher Version: 1.1.29
- Java Version: 8, 9, 16, 17
- Minecraft Version: does not apply
- Mod Loader: does not apply

**Comment by Eskaan** [comment]
https://minecraftstatus.com - session servers are down atm. Could you can reopen this if the issue persists after the server is back up please? If the issue persists, please also post console logs.
Also, you will have to click on "Log in with Microsoft" to log in with a MS Account.

**Comment by Thedoczek** [comment]
Everything is working fine now
