### ISSUE TITLE
Issues connecting to any server on any modded instance

### ISSUE THREAD

**Issue by Marsient** [killpowa/Twickt-Launcher#1494]
Whenever I try to connect to a server through any modded instance it fails to log in to the server and has the error message "failed to login the authentication servers are currently not reachable please try again"

I've tried to solve it using the instructions in [this](https://www.reddit.com/r/Minecraft/comments/o0wj63/failed_to_log_in_the_authentication_servers_are/) Reddit post, but it didn't help.  I'm not sure what to do to fix it.

I can connect to vanilla servers like Hypixel, but no modded ones.

**Comment by Eskaan** [comment]
As this is most likely not a GDL issue but a Minecraft one, I would like to redirect you to our Discord Server. Please reopen this issue if this issue turns out to be launcher-related.
