### ISSUE TITLE
adding mods bug

### ISSUE THREAD

**Issue by diemitze** [killpowa/Twickt-Launcher#1498]
so i imported a mod pack i made from courseforge when i look at the mod list i see all the mods and when i want to add a mod like jei its says i can added it but i have it already
![DesktopScreenshot (2)](https://user-images.githubusercontent.com/80318198/208492562-86c4c38e-31e4-4250-8d75-1a15aef57b6e.png)
 
![DesktopScreenshot](https://user-images.githubusercontent.com/80318198/208492564-5035aea3-cf4a-4532-afd7-38378866db10.png)

**Comment by Eskaan** [comment]
Please include more information (like in the report form)

**Comment by diemitze** [comment]
> Please include more information (like in the report form)

what els information do u need ?

**Comment by tanchevk** [comment]
Launcher version, operating system, link to modpack, minecraft version, modloader used, modloader version ect.
