### ISSUE TITLE
Minecraft not starting with GDLauncher

### ISSUE THREAD

**Issue by RimonsVirginity** [killpowa/Twickt-Launcher#1501]
so i tried opening minecraft this morning and i was stuck on the "mojang studios" page with the white loading bar that just keeps restarting. i thought it was a personal issue, but a friend tried and had the same issue. yes i tired closing and reopening, yes i tried redownloading GD launcher, yes i tried restarting my computer.
![image](https://user-images.githubusercontent.com/89324357/209191526-de30c26e-6046-4a88-92df-02715419b469.png)
![image](https://user-images.githubusercontent.com/89324357/209191699-0ddeefa0-cc3b-4d2f-bd17-b7fe0b4ce3c4.png)
![image](https://user-images.githubusercontent.com/89324357/209191736-73626388-fc58-4cd5-b9bf-a759fc2b20c3.png)
just keeps restarting

**Comment by Eskaan** [comment]
Please provide more information (like in the issue form).  I would like to have the logs too (`>_` on the top).

**Comment by RimonsVirginity** [comment]
It doesn’t provide a log. It’s not crashing. It’s just stuck on a never
ending loading screen

**Comment by RimonsVirginity** [comment]
okay just kidding, for some reason it works now ¯\_(ツ)_/¯
