### ISSUE TITLE
Unable to launch instance - error 255

### ISSUE THREAD

**Issue by PixelRave** [killpowa/Twickt-Launcher#1504]
**Describe the bug**

My minecraft instance will not launch anymore after updating all mods to 1.19.3. It throws this error listed below and the screenshot. This only happens when I updated the pack to 1.19.3 and also when I make a new pack in the same version. This error does not happen in lower versions of minecraft.

The error in console.

`actions.js:3286 ps stderr: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
actions.js:3286 ps stderr: SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/Pixel/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.15.0/log4j-slf4j2-impl-2.15.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.`

**To Reproduce**
1. Press play
2. Wait for launch
3. Error 255

**Expected behavior**
For minecraft to launch flawless.

**Possible solutions**
I have seen someone talking about this error and I have changed the file in question using [this](https://github.com/gorilla-devs/GDLauncher/issues/1491#issuecomment-1343431347)... And it still wont work.

**Screenshots**

https://imgur.com/a/9xosxWE

**Operating System:**
- OS: KDE neon
- Launcher Version: 1.1.29
- Java Version: 17 (Also tried latest java didn't work ether)
- Minecraft Version: 1.19.3
- Mod Loader: Fabric

**Comment by Eskaan** [comment]
So you did download the file he linked and put it into the right folder?
Also please provide the full logs (>_ on the top; console tab)

**Comment by PixelRave** [comment]
> So you did download the file he linked and put it into the right folder? Also please provide the full logs (>_ on the top; console tab)

Yes I have replaced the file and it still shows the same error.

here is the console log

[-1672521319143.log](https://github.com/gorilla-devs/GDLauncher/files/10327980/-1672521319143.log)

Also the crash log if it helps..

[crash-2022-12-31_14.02.36-client.txt](https://github.com/gorilla-devs/GDLauncher/files/10328022/crash-2022-12-31_14.02.36-client.txt)

**Comment by Eskaan** [comment]
These error logs look to me like the mod `wands` failed to load. Please try 1.19.3 with a fresh instance to confirm it is not a problem with your mods.

**Comment by PixelRave** [comment]
> 

It seems that was the mod! Thanks for the pointer. 

What is strange is this error still occurred a few weeks ago with no mods loaded. But now it seems to be fine.

**Comment by VicRious** [comment]
I am having the same issue with any modpackss, I dont know how to fix this

**Comment by blarfoon** [comment]
The legacy version of GDL is no longer supported. You can try the new one at https://gdlauncher.com
