### ISSUE TITLE
JAVA ERROR? Error: Signal Exits Code: 4294967295

### ISSUE THREAD

**Issue by ShadowPllayzYT** [killpowa/Twickt-Launcher#1505]
PLEASE HELP I AM A NOOB WITH JAVA LOGGING AND OTHER SO IF YOU CAN PLEASE WALK ME THROGH
4294967295
I just downloaded GDL Vers: 1.1.29
I think this is a java logging lib error mabye with log4j?
- [x] I searched the issue tracker for other issues covering my case
[ERROR] SLF4J: No SLF4J providers were found. SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details. SLF4J: Class path contains SLF4J bindings targeting slf4j-api version
![error1](https://user-images.githubusercontent.com/121742296/210161697-b5bd8f34-c5bb-4786-bd50-2e5bec964a2b.png)
s 1.7.x or earlier. SLF4J: Ingnoring binding found at [union:/C:/Users[Windows User]/AppData/Roaming/gdlauncher_next/datastore/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.15.0/log4j-slf4j2-impl-2.15.0.jar%23131!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation. END
- OS: Windows 10
- GDLauncher Version: 1.1.29
- Java Version: 8/16
- Minecraft Version: 1.19.3
- Mod Loader: Forge (44.0.48)

**Comment by ShadowPllayzYT** [comment]
![error2](https://user-images.githubusercontent.com/121742296/210161836-6837e33b-bf7c-4c68-9f97-a54b697c1e35.png)

**Comment by Eskaan** [comment]
See #1491
