### ISSUE TITLE
cant download any modpacks gdlauncher keeps crashing

### ISSUE THREAD

**Issue by hyperfrost12** [killpowa/Twickt-Launcher#1506]
- [ y] I searched the issue tracker for other issues covering my case
- [y ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**when ever i try to add a mod pack it will crash gd launcher and say cannot read properties (reading 'toString')/cannot read properties of undefined (reading 'toString').**
_A clear and concise description of what the bug is._

**To Reproduce**
1. Go to 'the plus (add instants'
2. Click on 'curseForge'
3. download any modpack and wait
5. See error

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_ i dont have a clue i don't code

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/121915619/210476819-15e58d3c-0213-4d77-9bf5-fbed221a4f05.png)

**Operating System:**
- OS: [e.g. Windows 11]
- Launcher Version: [e.g. v1.1.29]
- Java Version: [e.g. 8/17]
- Minecraft Version: [e.g. modpack any version i try]
- Mod Loader: [e.g. Forge]

**Additional context**
_Add any other context about the problem here._

**Comment by Fuzzypyro** [comment]
I am also having the same issue with the same error during installation of most modpacks. I am using the latest flatpak distribution. (v1.1.30)
