### ISSUE TITLE
Unable to use chat in Realms Servers.

### ISSUE THREAD

**Issue by GoldenAJF** [killpowa/Twickt-Launcher#1509]
- [ x] I searched the issue tracker for other issues covering my case
- [ x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When typing in a Minecraft Realm, I am given the error "Chat disabled due to missing profile public key. Please try reconnecting." I have tested and this doesn't happen in normal public Minecraft servers.

**To Reproduce**
Start an instance.
Join a Minecraft realm.
Try typing in chat.
You'll get the error in the chat.

**Expected behavior**
I am able to use chat in Minecraft Realm servers.

**Possible solutions**
No idea, I'm not a coder.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: SteamOS (Steam Deck
- Launcher Version: v1.1.29
- Java Version: I believe 17 (Launcher installed it for me)
- Minecraft Version: 1.19.3
- Mod Loader: Vanilla/Fabric

**Additional context**
I do have a custom directory on my Micro SD card, and GDLauncher is installed via Flatpak.

**Comment by nikoci** [comment]
This happens for me in normal servers as well, same procedure

Arch 6.1.6-arch1-1

**Comment by nikoci** [comment]
From what I read researching the cause of this, there seems to be an open issue over here [MC-252942](https://bugs.mojang.com/browse/MC-252942) meaning that this is not related to the launcher itself. I guess we'll just have to wait for it to be fixed. I've had no luck fixing the issue myself sadly.

The workaround suggested by many is setting `enforce-secure-profile` to `false` in server.properties but as are playing on a realm, sadly your out of luck.

**Comment by GoldenAJF** [comment]
Ah, unfortunate. Thanks for the help anyway though.

**Comment by shockthetoast** [comment]
@GoldenAJF @nikoci 

I'm don't believe this is the same issue. It's the same error, but those are reports of it preventing connection to the server/realm entirely, while in this case we can connect but not chat.

Also, if I connect to the same realm through the native Minecraft launcher, chat works fine, it's only an issue going through GDLauncher. And is still an issue when all mods are disabled.

**Comment by tcm151** [comment]
Having the same issue as well, native launcher works fine, vanilla release 19.4 install fresh doesn't work

**Comment by patritha** [comment]
im on vanilla 1.20 and my friends can use chat and i cant

**Comment by kalph208** [comment]
Same issue. Minecraft realm java edition. For some reason it happens if I go afk for a bit and come back and never log out. I have to shut the launcher and game completely down and restart the launcher and game to be able to chat again. Thats all I can say.

**Comment by FaithInMotion** [comment]
Still an issue as well. I am able to chat when using the main minecraft launcher, but not GD launcher. I've been switching between the two to see if I can get one to force recognition of the other.

My best guess is that is has to do with the way we sign into GD Launcher and it's ability to pass credentials to the server. That may be a bit of a "duh" idea tho lol.

**Comment by Green-de-la-Bean** [comment]
this is still an issue, both me and my friend have it when using GD
