### ISSUE TITLE
gdlauncher from snap doesn't start

### ISSUE THREAD

**Issue by zulrang** [killpowa/Twickt-Launcher#1510]
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Launcher fails to start

**To Reproduce**
1. Install Ubuntu 22.04.1 LTS x86_64 fresh
2. Install gdlauncher using snap
3. Try to start gdlauncher
4. Nothing happens, no errors

**Expected behavior**
The software should start

**Possible solutions**
?

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: Ubuntu 22.04.1 LTS x86_64
- Launcher Version: 0.10.3-beta
- Java Version: openjdk version "18.0.2-ea"

**Comment by Eskaan** [comment]
I think the snap package is abandoned. The version shown is way outdated; current is v1.29.
