### ISSUE TITLE
Unable to install modpacks to Curseforge Security check breaking INSTANCE SKP downloads

### ISSUE THREAD

**Issue by WonderDog** [killpowa/Twickt-Launcher#1511]
- [x ] I searched the issue tracker for other issues covering my case
- [x ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Cant install mod pack (Enigmatica 6, NTC2,  Sky Capsule Project) as download of files of no third party D/L get stuck on the continuously refreshing  Security check page (for at least 45 minutes)

If you close the window you get an option to retry of abort.

There is no option to skip the downloads.

Nothing in the console while the download browser window is open.

When you close the window the only error is 
`Error: Download Aborted by the user
    at OptedOutModsList.js:220:30`

**To Reproduce**
1. Select new instance or import ZIP (tried both)
2. Follow instructions
3. If there are any restricted from 3rd party mods the sub window will continuously reload the Curseforge Security check.
4. Will eventually time out but can take 1/2 hour

**Expected behavior**

Does time out but takes a long time.

**Possible solutions**

Ability to skip the files to be downloaded manually later by the user

**Screenshots**
![image](https://user-images.githubusercontent.com/8510324/212503429-68c1aac4-7c54-497e-890a-8c849d61af71.png)

**Operating System:**
- OS: Windows 10
- Launcher Version:  v1.1.29
- Java Version: OpenJDK, 1.8.0-312 / 1.7.0.1
- Minecraft Version: 1.16.5 / 1.18.5
- Mod Loader: Forge

**Additional context**
_Add any other context about the problem here._

**Comment by zulrang** [comment]
Having the same issue with All of Fabric 6

**Comment by Alek05** [comment]
Having this issue when importing most custom packs

**Comment by Eskaan** [comment]
Duplicate of #1367 (pinned issue)
