### ISSUE TITLE
400 Errors When trying to create a fresh 1.19.3 Instance

### ISSUE THREAD

**Issue by aedanflynn** [killpowa/Twickt-Launcher#1519]
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Any attempt to download a fresh 1.19.3 instance with no previous 1.19.3 instance installed, causes a 400 error when trying to download all game files. This happens for any type as well, vanilla, forge, fabric, etc. Other versions show no issues.

**To Reproduce**
1. Remove all 1.19.3 instances from GD Launcher or have a fresh install.
2. Create a new instance for 1.19.3, either vanilla, forge or fabric.
3. Verify the download runs slowly and check the console to find 400 errors.

**Expected behavior**
No 400 errors on downloading game files.

**Possible solutions**
I assume an endpoint is aimed at the wrong location or Mojang moved the file locations.

**Screenshots**
<img width="1414" alt="gderror" src="https://user-images.githubusercontent.com/14184015/213472033-666cd418-445c-40c0-9263-a26d050627d2.png">

**Operating System:**
- OS: Windows 10
- Launcher Version:  v1.1.29
- Java Version: 8
- Minecraft Version: 1.19.3
- Mod Loader: Vanilla, Forge and Fabric

**Additional context**
This seems to have started around the 15th. I have a number of friends that were able to successfully create 1.19.3 instances prior to that date but anyone after that time seems to receive the same issue.

**Comment by Eskaan** [comment]
Duplicate of #1513 (pinned)
Maybe search for closed issues too next time :)

**Comment by aedanflynn** [comment]
> Duplicate of #1513 (pinned) Maybe search for closed issues too next time :)

The issue isnt solved however. A fresh install and update of GDLauncher still results in the same errors even reproduced this morning.

**Comment by Eskaan** [comment]
The issue is resolved in dev and thus in the development issue tracker. It will be official with the next release.
You can always grab the latest development build ant use that.
