### ISSUE TITLE
Curseforge opted-out mods “Checking if the site connection is secure” is not given enough time to properly finish

### ISSUE THREAD

**Issue by tanchevk** [killpowa/Twickt-Launcher#1526]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When installing modpacks and/or mods, curseforge sometimes mandates a connection check, courtesy of Cloudflare. When this occurs, GDlauncher falsely assumes nothing is wrong and refreshes the page after a given amount of time, however this interferes with the connection check and results in an infinite loop of GDlauncher trying to download the opted-out mod but being unable to properly verify its connection.

**To Reproduce**
1. Open GDlauncher
2. Click on the new instance button
3. Select modpacks (easiest way to witness, also works with mods)
4. Select any modpack with opted-out mods (for example, Light Craft)
5. Wait for opted out mods modal
6. Click confirm
7. Observe as GDlauncher enters an infinite loop of verification attempts
8. After a given amount of attempts, GDlauncher will simply inform you of a failed download

**Expected behavior**
GDlauncher should, optimally, allot more time for the verification prompt (this one doesn't even require input)

**Possible solutions**
Detect this page (utilizing request and response headers, maybe) and increase the time between refreshes when it detects the verification prompt

**Screenshots**
![image](https://user-images.githubusercontent.com/93494094/214378729-60266dda-5b09-475a-a93e-534988782ef3.png)
![image](https://user-images.githubusercontent.com/93494094/214378782-8e02d933-466a-4e74-b577-26f1dc890a2a.png)
(Ignore background applications, forgot to close)
![image](https://user-images.githubusercontent.com/93494094/214379192-45ca43bb-7781-4536-a6bc-381ea70e7592.png)
![image](https://user-images.githubusercontent.com/93494094/214378841-ed4b800f-8404-4059-a462-32b60e9398b3.png)
![image](https://user-images.githubusercontent.com/93494094/214379056-232188b1-a65c-4db8-b107-8a8a00ad8e6f.png)

**Operating System:**
- OS: Windows 11 Home 22H2 22621.1105
- Launcher Version: v1.1.25
- Java Version: 19
- Minecraft Version: 1.19.3 (observed on other versions as well)
- Mod Loader: Fabric (occurs on Forge also)

**Comment by Eskaan** [comment]
Duplicate of #1513
Also, the latest version is v1.1.29 / v1.1.30-beta.1 ;)

**Comment by tanchevk** [comment]
oops mb my dumb ass forgot to update
