### ISSUE TITLE
add an option to just not install opted out mods in modpacks.

### ISSUE THREAD

**Issue by Kokonico** [killpowa/Twickt-Launcher#1532]
- [yes] I searched the issue tracker for other issues covering my case.

**Is your feature request related to a problem? Please describe.**
_I'm always frustrated when I download a big modpack then midway "fresh animations" or something opts out and i can only try to download it or cancel the entire modpack from installing._

**Describe the solution you'd like**
_A third option to continue installation without the mod as gdlauncher's workaround isn't the best and sometimes bugs out._

**Describe alternatives you've considered**
_N/A._

**Additional context**
_N/A._

**Comment by Eskaan** [comment]
Is it enough for you if I tell you that in the lastest version it offers you to download them manually after it failed and you can always press "continue" even if not downloading it manually?

**Comment by Kokonico** [comment]
yes, thank you!
