### ISSUE TITLE
Referenced memory could not be written

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1533]
- [X] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When exting GDLauncher after reopening (with "Hide Launcher While Playing" enabled), a memory reference read error will be raised. This error is fatal, but is not severe - doesn't matter much because the program is being closed anyway.

This could be a very specific issue with a specific version of something causing this.

This only occurs when a profile is launched, closed, and the launcher is reopened automatically and then closed by user. It does not happen if the launcher is opened, and then closed by user. Nor if the "Hide Launcher While Playing" is disabled, and the launcher closes automatically.

**To Reproduce**
1) Open GDLauncher.
2) Ensure "Hide Launcher While Playing" is enabled in settings.
3) Play any modpack/profile.
4) Exit the game.
5) Wait for the launcher to show up.
6) Exit the launcher with the "X" button in top right.
7) Memory reference error shows up.

**Expected behavior**
No error shown when exiting.

**Possible solutions**
None that come to mind.

**Screenshots**
![image](https://user-images.githubusercontent.com/47798787/215375881-2f42aa00-b386-4383-8e1b-5cd9fd880fff.png)

**Operating System:**
- OS: Windows 10 20H2 (19042.631)
- Launcher Version: 1.1.30
- Java Version: java 17.0.1 2021-10-19 LTS
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
N/A

**Comment by Eskaan** [comment]
Possibly linked to #1054

**Comment by Supermarcel10** [comment]
Closing stale issue. For those that don't know - GDLauncher is out of support. Use [GDLauncher-Carbon](https://github.com/gorilla-devs/GDLauncher-Carbon) instead.
