### ISSUE TITLE
Exception in thread "Narrator" game crash

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1539]
- [X] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
I have 16GB of Memory dedicated to the minecraft instance.
When on my server in spectator mode, teleporting around to players using 1-7, sometimes the minecraft instance crashes and displays the message `Exception in thread "Narrator" AL lib: (EE) alc_cleanup: 1 device not closed`. The instance does not seem to run anywhere close to the maximum memory heap set.

Loading excessive number of chunks does not seem to affect this issue. I've tested this by using `/flyspeed fly 10` and flying around, but despite loads of chunks loaded the game never crashed.

I'm not quite sure what the Narrator class/method/library has to do with anything to this issue, since I don't see it related in any way.

Server runs with default settings of render distance 12.

**To Reproduce**
To reproduce, a server with the modpack `Create: Above and Beyond` and a few players would be required.

1. Download, install and run the modpack "Create: Above and Beyond".
2. Join a server where you have access to gamemode spectator.
3. Enter spectator mode.
4. Ensure players teleported-to are in different locations (chunk-wise).
5. Rapidly teleport from player to player. (As you would normally meanwhile moderating players to check up on them).
6. Game will crash from time to time with the shown error message.

**Expected behavior**
No crash should occur.

**Possible solutions**
Not quite sure of the possible solutions. I'd most likely inspect what the "Narrator" class/methods/library have to do with anything related to this issue and follow on from there.

**Screenshots**
![image](https://user-images.githubusercontent.com/47798787/216791078-c9ed7134-3aa7-4b1d-951a-f159322f9229.png)

**Operating System:**
- OS: Windows 10 20H2 (19042.631)
- Launcher Version: 1.1.30
- Java Version: java 17.0.1 2021-10-19 LTS
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
N/A

**Comment by Eskaan** [comment]
The issue does not seem like a launcher issue to me either.

This issue tracker is not for Minecraft but only launcher issues. Please use our Discord channels or contact the responsible mod author directly. That is why we have the two check marks above.

If you think this is a Launcher related issue, please reopen this issue and elaborate further (logs recommended).
