### ISSUE TITLE
App refuses to start on Wayland

### ISSUE THREAD

**Issue by menguele** [killpowa/Twickt-Launcher#1547]
**Describe the bug**
App wont start if its under Wayland (Snap version)

**To Reproduce**
Install GDLauncher through snap and launch

**Operating System:**
- OS: OpenSUSE 
- Java Version: GraalVM 8, OpenJDK 17

Installed the RPM version and it ran just fine, although Yast says it will break because 'libuuid' isn't available, is just an issue with different package naming between Fedora/RedHat and SUSE

**Comment by Eskaan** [comment]
I think the snap package is outdated.
See #1510.
Please fill out the full issue form (or at least parts important for your issue). The issue form also asks you to search for other issues regarding your case. Please do that before opening an issue.
