### ISSUE TITLE
Couldn't look up profile properties for com.mojang.authlib

### ISSUE THREAD

**Issue by JoJoaoBerserk** [killpowa/Twickt-Launcher#1550]
- [ ] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When loading the instance and my single-player world, I noticed that my skin did not load, and checking in Developer Tools has registered the following message:
<log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService" timestamp="1677433954019" level="WARN" thread="Worker-Main-9">
     <log4j:Message><![CDATA[Couldn't look up profile properties for com.mojang.authlib.GameProfile@f85bb40[id=9e5dc5f8-ed9a-43ba-840c-a944daf942b5,name=JoJoao_Agiota,properties={},legacy =false]]]></log4j:Message>
     <log4j:Throwable><![CDATA[com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
[latest.log](https://github.com/gorilla-devs/GDLauncher/files/10834415/latest.log)

**To Reproduce**
1. Go to 'GDLauncher'
2. Click on 'JoJoaoAgiota Modpack'
3. Click on 'Play'
4. Loading the game
5. See error in Developer Tools/latest.log

**Expected behavior**
Being able to play with my skin

**Possible solutions**
I don't know, but I generated JoJoaoAgiota Modpack-1.0.zip by GDLauncher's Export Pack tool so you can test it.
[JoJoaoAgiota Modpack-1.0.zip](https://github.com/gorilla-devs/GDLauncher/files/10834410/JoJoaoAgiota.Modpack-1.0.zip)

**Screenshots**
![2023-02-26_14 52 54](https://user-images.githubusercontent.com/125163252/221428476-756a77d8-85c3-40be-8f43-48b656c6d73d.png)

**Operating System:**
- OS: Windows 11
- Launcher Version: v 1.1.30
- Java Version: \GDLauncher\java\17.0.1+12
- Minecraft Version: 1.19.2
- Mod Loader: Forge 43.2.6

**Additional context**
I created this modpack with 176 mods all in the latest version.
In the latest.log file I noticed the following record at the beginning of the file:
[14:50:28] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationException: com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/player/attributes due to Connect timed out

I also created a new instance using only forge 43.2.6, and the problem also occurs.
[latest.log](https://github.com/gorilla-devs/GDLauncher/files/10834454/latest.log)

**Comment by Eskaan** [comment]
I think this might be an issue on your side. (If this hasn't been resolved yet), could you try opening above url in your browser and see what response you get there? Also, is there anything special about your internet connection we should know?

**Comment by JoJoaoBerserk** [comment]
> I think this might be an issue on your side. (If this hasn't been resolved yet), could you try opening above url in your browser and see what response you get there? Also, is there anything special about your internet connection we should know?

I restarted my router, and tried to access the link:
https://api.minecraftservices.com/player/attributes
But still displays the message:

This page is not working the problem persists, contact the site owner.
Http error 401

**Comment by Teapot4195** [comment]
Returning 200 ok on my end. I'm guessing it's a firewall blocking it somewhere.

**Comment by Eskaan** [comment]
I think the 401 Unauthorized is normal for a unmodified browser request, I get that too. You could try logging out and back in, but a Timeout error is in most cases on the users side.

**Comment by JoJoaoBerserk** [comment]
> I think the 401 Unauthorized is normal for a unmodified browser request, I get that too. You could try logging out and back in, but a Timeout error is in most cases on the users side.

I installed Forge and used the Xbox APP launcher, and the problem also occurs, so it really is a problem with my connection, thanks for the help, I will try to check if it is something on my computer, router or internet provider.

**Comment by JoJoaoBerserk** [comment]
I was looking in the Forge Modloader forum and found a post with the same problem, and a person advised to disable the IPV6 protocol and now he is authenticating the account again using Forge, my skin returned to display and I managed to enter my dedicated server.
For those who don't want to disable the IPV6 protocol you can use the argument in the launcher:
-Djava.net.preferIPv4Stack=true
