### ISSUE TITLE
Changing the user data path...

### ISSUE THREAD

**Issue by menoobslayer** [killpowa/Twickt-Launcher#1554]
Is there a reason changing user data path DOESN'T actually change the userdata path?
Even if you change it all it f@#$@# does is create a copy of the contents of the first folder...

The default directory is still mandatory for the program to work, if you delete the default directory then it just resets the launcher back to like its a fresh install and recreates it...

Seriously is this pre-alpha or something?

**Comment by Eskaan** [comment]
See [moderation warning](https://github.com/gorilla-devs/GDLauncher/issues/1553#issuecomment-1457619739)
