### ISSUE TITLE
Install directory.

### ISSUE THREAD

**Issue by menoobslayer** [killpowa/Twickt-Launcher#1555]
How can you claim to be user friendly/made for usability if you can't even choose an install directory?

Not everyone has a default directory with limitless space to spare, your program doesn't even have an option to choose the installation path, even if you try to manually move the files elsewhere and tell the program the new path it STILL is forcing the usage of the default directory.

**Comment by Eskaan** [comment]
See [moderation warning](https://github.com/gorilla-devs/GDLauncher/issues/1553#issuecomment-1457619739).
