### ISSUE TITLE
Updating mods triggers Bitdefender Antimalware

### ISSUE THREAD

**Issue by isaaclepes** [killpowa/Twickt-Launcher#1556]
- [X] I searched the issue tracker for other issues covering my case
- [?] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When updating mods within GDLauncher, the behavior triggers Bitdefender Antivirus.
Antimalware static engines have detected a potential security breach, generated by this malicious artifact: gdlauncher.exe.

![image](https://user-images.githubusercontent.com/54421422/225056515-0f8ea455-8a74-4e83-9dda-2a58b9e55a47.png)
![image](https://user-images.githubusercontent.com/54421422/225056648-90985de2-9ba9-4f1e-aa01-7475792c5d2c.png)

I have whitelisted the application, but this detail may help you prevent GDLauncher from triggering AV in the future.

I would also like to know why GDLauncher was seen using the Remote Desktop Protocol, as that one is particularly strange.
https://attack.mitre.org/techniques/T1021/001/

**Comment by Eskaan** [comment]
Minecraft Launchers generally tend to get caught as Malware, as in the end they download and execute the Game files. This is a won't fix, there is basically nothing we can do to prevent antivirus detection for such a small program.

I, personally, am not a big fan of Antivirus programs anyways especially when they're not even open source.

**Comment by Eskaan** [comment]
Duplicate of #736 btw.
