### ISSUE TITLE
Installation takes awhile installing Forge for modpacks and reinstalls Forge when starting instance and then loops

### ISSUE THREAD

**Issue by SuperWario128** [killpowa/Twickt-Launcher#1560]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
Everytime I go to install a new instance, doesn't matter if it's an imported zip or not, it will take a very long time to install and when it's supposedly installed, it will go through the steps to reinstall Forge upon starting said instance. Then once it get through installing again, it starts over with installing Forge again.

**To Reproduce**
1. Proceed to install a new instance that is Forge based (doesn't matter if it's an imported zip or not).
2. Follow the steps normally required to install a new instance.
3. Let things attempt to install.
4. See the loop happen at the end of "installation". Closing out and relaunching does not resolve issue either.

**Expected behavior**
_Pack is supposed to be installed and playable.

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: Windows 11
- Launcher Version: 1.1.29
- Java Version: 17
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Additional context**
_Add any other context about the problem here._

**Comment by Eskaan** [comment]
Your launcher version is outdated. You may need to upgrade manually by reinstalling. Your issue is most likely #1513.
