### ISSUE TITLE
Downloading game files step completes very slowly

### ISSUE THREAD

**Issue by Ethan-Vann** [killpowa/Twickt-Launcher#1563]
- [x ] I searched the issue tracker for other issues covering my case - There was a similar issue talking about using a mirror but it didn't seem to be covering the same severity and has been stale for nearly 2 years
- [x ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
"Downloading game files" step takes a very long time even on good connection
In this example case downloading crash landing took over an hour to complete.

**To Reproduce**
select pack to install
monitor download speed of resources 

**Expected behavior**
Downloading single instance does not take over an hour

**Possible solutions**
Not sure if it is just a host speed issue problem if it is then no real solution otherwise solve the bug causing the issue

**Screenshots**
Internet speed tested
![internet speed test](https://user-images.githubusercontent.com/22735513/234797374-673cad08-0f42-493f-aa34-7ef9fa107b0a.png)
Picture taken showing progress when screenshots were taken
![download progress](https://user-images.githubusercontent.com/22735513/234797419-0e319eb5-656c-4e51-9105-9992e2cb1fc7.png)
picturing showing when download began
![when download started](https://user-images.githubusercontent.com/22735513/234797539-55adb550-8268-48a8-ac70-87a8b27be46c.png)
picture showing current time when screenshots were displayed
![current time](https://user-images.githubusercontent.com/22735513/234797597-20fa3314-4245-410a-b9d3-76fc06fd08b4.png)

**Operating System:**
- OS: Windows 10
- Launcher Version: 1.1.29
- Java Version: jdk shipped with launcher
- Minecraft Version: 1.6.4
- Mod Loader: Forge

**Additional context**
Concurrent downloads is set to 20 and I have tested other values as well

**Comment by Eskaan** [comment]
I think your issue might be the outdated version. We recently had an issue by using the wrong protocol to download stuff. See [this issue](https://github.com/gorilla-devs/GDLauncher/issues/1513) and the [latest release](https://github.com/gorilla-devs/GDLauncher/releases/latest)

I assume this is a dup of mentioned issue. If the issue persists on the newer version please reopen the issue or write a comment for me to do it.
