### ISSUE TITLE
Fail to access world error on Create : Astral modpack

### ISSUE THREAD

**Issue by Gorgoam** [killpowa/Twickt-Launcher#1564]
Hello ! I searched everywhere in hope to find a solution to my problem but didn't find any... I'm currently using the CREATE : ASTRAL modpack + around 10 mods I added myself in 1.18.2 fabric minecraft version (modpack version : v2.0.4). I am using it on steam deck, so I am new to Linux. I can launch the modpack correctly but when it comes to creating a world, it opens the menu of world creating and when I click to create the world, it just takes me back to the main menu and shows a pop up saying "Failed to access world" twice. The weird thing is that it does create a world in the "saves" file, but there is just a "session.lock" file in it, and it is empty. I tried launching the modpack on my computer (windows) and create a world, and it works just fine. Then I tried to import a world file from my computer to my steam deck, but it just ignores the fact that I got a world in the "saves" file and shows me the creating world menu. What's really strange is that I can perfectly join a server with all the mods and modpack and it works fine. I just can't create a solo world. Then I tried to move the instances file on a different memory card, but it didn't change anything. Every other modpack on gdlauncher are working, except this one. By the way, I don't get any crash or error code or log, just this weird "Failed to access World" on the top right corner of the screen twice... And now I have got the impression that it takes much more time to load on the loading screen (around 15 minutes)... before it would just take 5 minutes...

![1682849038707660925786124194900](https://user-images.githubusercontent.com/132196272/235347326-7016a9fc-9290-4920-b1e3-932a6986a04a.jpg)

I don't understand why it couldn't work, but there surely is a problem about the files or the permissions, because every other modpacks works, and this modpack works on my windows computer.

Thank you for your time and your answers.

**Comment by Eskaan** [comment]
I can't really help you with not much information. Even tho this is most likely not a launcher issue, I would appreciate logs from after you tried creating the world (use `>_` at the top to access the console).

**Comment by Gorgoam** [comment]
Well, a lot of things are happening in the logs ! I start giving you the log at the first error, when the world creation menu OPENS : 

![20230501_090727.jpg](https://user-images.githubusercontent.com/132196272/235420954-acf461cb-36bd-4a67-853e-1c761a71466d.jpg)

Then, when I clicked on create a New world, this happened :

![20230501_090920.jpg](https://user-images.githubusercontent.com/132196272/235421044-f92ce385-7c88-44e2-bca0-9a702b36c380.jpg)

And afrerwards this happened too :

![20230501_090954.jpg](https://user-images.githubusercontent.com/132196272/235421099-e2d47218-b676-41db-b766-879610ac2f22.jpg)


Hope that's not too blurry...

**Comment by Eskaan** [comment]
You might try to use the "repair instance" feature (be sure to do a backup before using it). If the doesn't work, I would say it's one of your mod's fault and thus not a launcher issue (I would close this issue). I recommend to checkout our issue if that is the case.

**Comment by Gorgoam** [comment]
> You might try to use the "repair instance" feature (be sure to do a backup before using it). If the doesn't work, I would say it's one of your mod's fault and thus not a launcher issue (I would close this issue). I recommend to checkout our issue if that is the case.


Thank you a lot ! I did a repair and now it works ! I don't know why it wouldn't work first, but that is not a problem anymore. Thank you so much ! I am going to close this issue now.

**Comment by Eskaan** [comment]
It is likely that at some point one of the game files corrupted. The repair checks all files and downloads them again to ensure integrity.
