### ISSUE TITLE
I can't log in to my Microsoft account??

### ISSUE THREAD

**Issue by FiveNights21611** [killpowa/Twickt-Launcher#1565]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_I was trying to add my alt account to GD, but it keeps telling me there was an Xbox token error. The account owns Java Edition_

**To Reproduce**
Not really a way to reproduce it, and I'm not sure what's causing it

**Expected behavior**
_It'll throw an error about Xbox Token Services and not let me login. I can login to my main account, it just won't let me login to my alt. Even tried using it as the main login, didn't help_

**Possible solutions**
_No Clue_

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Operating System:**
- OS: [Windows 10]
- Launcher Version: [v1.1.30]
- Java Version: [N/A]
- Minecraft Version: [N/A]
- Mod Loader: [N/A]

**Comment by Eskaan** [comment]
Dup of #1116
