### ISSUE TITLE
Signal Exits error?? 4294967295

### ISSUE THREAD

**Issue by IceyEXE** [killpowa/Twickt-Launcher#1566]
- I searched the issue tracker for other issues covering my case
- this is my first time writing a bug report so apologies if it's not good.

**Describe the bug**
whenever I go to launch my Minecraft instance, it results in this crash. other instances run without issue. This is an instance i have run before with no issues, I have multiple hours on it and do not want to lose my progress.

**To Reproduce**
I have no idea how to reproduce it.

**Expected behavior**
I expected my Minecraft instance to run normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/132343759/235627141-80366891-7ec2-4656-9f04-025dcf195325.png)
I do not know how to share the entire error message.

**Operating System:**
- OS: Windows 10
- Launcher Version: 1.1.30
- Java Version: 8/17 
- Minecraft Version: 1.19.2
- Mod Loader: Fabric, 0.14.19

**Additional context**
I did add one extra mod before I encountered the error, but removing the mod did not fix the issue. I was playing on my installation a few minutes prior.

**Comment by Eskaan** [comment]
Could you please post console logs after the instance crashed (use `>_` at the top to get to the console)?

**Comment by IceyEXE** [comment]
What part of the console is that? the red bit?

**Comment by Eskaan** [comment]
If possible, put it all into a file and upload it by dragging it into here. The log messages can also contain helpful clues.

**Comment by IceyEXE** [comment]
[log message file.txt](https://github.com/gorilla-devs/GDLauncher/files/11380806/log.message.file.txt)

like this?

**Comment by Eskaan** [comment]
I can‘t really help you here. This does not look like a launcher issue but an issue with your instance itself. I can only recommend you to look if the mod is really removed.
