### ISSUE TITLE
Minecraft crashing on 1.8.9

### ISSUE THREAD

**Issue by Magnus1001** [killpowa/Twickt-Launcher#1572]
Minecraft 1.8.9 crashes when you move when using Optifine.

1. Join a server
2. move
3. crashed game
4. See error: "AL lib: (EE) alc_cleanup: 1 device not closed" with a code of, "4294967295"

Normally, the game doesn't crash.

![Capture11](https://github.com/gorilla-devs/GDLauncher/assets/123913125/3caf0f9f-fcc6-4dec-aaa4-e42571896e87)

**Operating System:**
- OS: [Windows 10]
- Launcher Version: [v1.1.30]
- Java Version: [8]
- Minecraft Version: [1.8.9]
- Mod Loader: [Forge]

It was working earlier. The crash specifically occurred in the Hypixel Wool Wars lobby.

**Comment by Eskaan** [comment]
Can you reproduce the crash, tell us how to do it and send the logs please?

**Comment by Magnus1001** [comment]
> 

If you join the Hypixel Wool Wars lobby with Optifine and a custom resource pack, the game crashes once you move.
[latest.log](https://github.com/gorilla-devs/GDLauncher/files/11895732/latest.log)

**Comment by Eskaan** [comment]
I think this has something to do with your mods. Does it work with a fresh instance?
Btw the log contains an absurdly large stack trace of all fatal errors. Something is going *very* wrong there.

**Comment by Magnus1001** [comment]
> I think this has something to do with your mods. Does it work with a fresh instance? Btw the log contains an absurdly large stack trace of all fatal errors. Something is going _very_ wrong there.

Yes this only happens with optifine.

**Comment by Eskaan** [comment]
Then you should ask the optifine devs, this dosen't seem like a launcher issue.
