### ISSUE TITLE
Trouble when building from source

### ISSUE THREAD

**Issue by PassiveLemon** [killpowa/Twickt-Launcher#1573]
- [x] I searched the issue tracker for other issues covering my case
- [ ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
When following the building instructions, running `npm run release` will give an ENOENT error.
**To Reproduce**
1. Get the archive
2. Verify you have the dependencies
3. Run `npm i --legacy-peer-deps`
4. Run `npm run release`
5. See error

**Expected behavior**
It finishes building so I can observe the file structure

**Possible solutions**
No clue

**Screenshots**
Full output here: https://pastebin.com/LeKvFuR0

**Operating System:**
- OS: NixOS 23.11
- Launcher Version: 1.1.30
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
I am currently working on packing this with Nix to put onto the Nixpkgs repo. I do not know the file structure and where the binary is located after being built so I am building it myself on my host. I believe I have all of the correct dependencies listed. It is an ENOENT spawn error with the 7za module at `node_modules/7zip-bin/linux/x64/7za` but that does exist at the location. In that log, there also might be other issues I'm not catching lol.

**Comment by Eskaan** [comment]
Huh, never encountered that before.
Could you try running `npm install --legacy-peer-deps` again and check if a similar path exists?

**Comment by PassiveLemon** [comment]
I deleted that module, and reran and it does download it. Even made sure that it has execution permissions, which it does. Not sure whats going on

**Comment by Eskaan** [comment]
So the file exists initially, but get's removed somewhere alsong the build process?

**Comment by PassiveLemon** [comment]
It seems unlikely to me that it is getting removed as it's still here after the run fails

**Comment by Eskaan** [comment]
You said " that does exist at the location" so I assumed it did not exist at some point.

**Comment by PassiveLemon** [comment]
I reran the run command and checked the Last Modification tag which shows the date/time from when I deleted it and reran it earlier

**Comment by PassiveLemon** [comment]
All I really need is just the file structure when its been built so I know where to get the binary, images, etc so I can wrap it

**Comment by PassiveLemon** [comment]
All I really need is just the file structure after its been built so I know where everything is to package it if you don't mind

**Comment by Eskaan** [comment]
I think everything you need should be in the `deploy` folder. But I can't look right now.
