### ISSUE TITLE
Error: Error occurred while logging in Microsoft.

### ISSUE THREAD

**Issue by Supermarcel10** [killpowa/Twickt-Launcher#1576]
- [X] I searched the issue tracker for other issues covering my case
- [X] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
The launcher logged me out and won't allow me to log back in.

**To Reproduce**
1. Open launcher.
2. Press "Sign in with Microsoft"

**Expected behavior**
The launcher shouldn't log out every time it's restarted. The launcher should also allow user to log in.

**Possible solutions**
Might be related to other issues such as #1449 and #1162.

**Screenshots**
![image](https://github.com/gorilla-devs/GDLauncher/assets/47798787/9a42b96b-024e-4131-a0f3-aca5b0d2f86f)

**Operating System:**
- OS: Windows 10
- Launcher Version: 1.1.30
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A

**Comment by karpada2** [comment]
I have the exact same issue, did you figure out how to fix it? I personally can't log in at all

**Comment by Supermarcel10** [comment]
Didn't really find a reliable solution. I tried reinstalling and just stuck with logging in every time.

**Comment by karpada2** [comment]
Welp :/ guess we are both stuck with that

**Comment by Supermarcel10** [comment]
Closing stale issue. For those that don't know - GDLauncher is out of support. Use [GDLauncher-Carbon](https://github.com/gorilla-devs/GDLauncher-Carbon) instead.
