### ISSUE TITLE
Modpacks utilizing Neoforge installer start a vanilla instance instead of modpack

### ISSUE THREAD

**Issue by TGurl** [killpowa/Twickt-Launcher#1591]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_Modpacks using the NeoForge modloader do not work. For example FTB presents Direwolf20 1.20 does not work out of the box as they utilize the neoForge 1.20.1-47.1.79 installer_

**To Reproduce**
1. Go to 'Add a new instance -> FTB -> select FTB presents Direwolf20 1.20 '
2. Click on 'start' after installation is finished
3. A vanilla version of Minecraft 1.20.1 will start instead of the modpack

**Expected behavior**
_The launcher installs the mods using the NeoForge installer._

**Possible solutions**
_Implement the Neoforge installer next to Forge._

**Screenshots**
_None_

**Operating System:**
- OS: Arch Linux, kernel 6.1.55-1-lts
- Launcher Version: v1.1.30
- Java Version: 17.0.8.1
- Minecraft Version: 1.20.1
- Mod Loader: NeoForge 1.20.1-47.1.79

**Additional context**
_The modpack does work with a workaround:_

1.  Create a new instance using Forge
2.  Copy over all necessary folders/files from the FTB instance to the newly created one
3.  Start the new instance.

_More information about Neoforge: https://neoforged.net/._

**Comment by steffenlindemann** [comment]
I have the same issue. Also with the direwolf 20 1.20 ftb pack.

**Comment by Eskaan** [comment]
Sadly, we no longer support FTB. They have asked us to remove the support (and in the dev version it already is). They also changed their API so it's no longer possible to use the old support.

**Comment by TGurl** [comment]
Understandable when talking about FTB. The only thing is some mods (and maybe later other modpacks) are already moving to Neoforge. Maybe it's still important to check this as it's very likely Neoforge and Forge won't be compatible in the future. Just a thought.

**Comment by Normal69** [comment]
> Understandable when talking about FTB. The only thing is some mods (and maybe later other modpacks) are already moving to Neoforge. Maybe it's still important to check this as it's very likely Neoforge and Forge won't be compatible in the future. Just a thought.

Indeed I am now trying to download the non-neoforge mods with no choice over the matter.
