### ISSUE TITLE
Forge: Support the new Neoforge project

### ISSUE THREAD

**Issue by QuentiumYT** [killpowa/Twickt-Launcher#1599]
- [X] I searched the issue tracker for other issues covering my case.

Everything is in the title, now that forge is kinda abandoned, we should switch to neoforge mod loader (https://neoforged.net/)

**Comment by Eskaan** [comment]
Related issue: #1591

**Comment by QuentiumYT** [comment]
Will look for GDLauncher carbon for this feature :)
