### ISSUE TITLE
How to run an instance of the game using a graphics card on lubuntu?

### ISSUE THREAD

**Issue by mernok1** [killpowa/Twickt-Launcher#1602]
I have a problem. I'm using lubuntu and I'm trying to install nvidia drivers and run the installed game on my graphics card but it doesn't work How to do it?

**Comment by Eskaan** [comment]
You might have a look on #969 (windows case)

**Comment by Sgale952** [comment]
If you are using AMD's iGPU and Nvidia's dGPU, you can try running launcher through the console with those flags:
```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia gdlauncher
```
You can also modify the gdlauncher.desktop file to use the flags automatically:
```
Exec=env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia /usr/bin/gdlauncher --dummy-flag %U
```
These flags require nvidia and amdgpu drivers
_Maybe these flags work with Intel's iGPUs as well, but I have no way to verify it_
