### ISSUE TITLE
Automatic Setup Stuck

### ISSUE THREAD

**Issue by silverwomper** [killpowa/Twickt-Launcher#1605]
- [✔] I searched the issue tracker for other issues covering my case but didn't find one related to it.
- [✔] This is a Launcher issue

**Describe the bug**
Launcher opens and after selecting "Automatic Setup" it gets stuck on "Java 8 - downloading"

**Operating System:**
- OS: [Windows 10 Pro]
- Launcher Version: [1.1.30]

**Steps I've tried but failed**
Reinstalling GDLauncher
Restarting Computer
Running as Admin
Restarted my network

**Comment by siongadev** [comment]
Edit: Fixed the issue, my firewall was blocking the download's
