### ISSUE TITLE
[Visual] When have too much RAM, the launcher does not fill it correctly

### ISSUE THREAD

**Issue by Guztaver** [killpowa/Twickt-Launcher#1608]
- [x] I searched the issue tracker for other issues covering my case
- [x] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
_Basically, the launcher does not have a good interface when you have a lot of RAM in your system._

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Java'
3. Scroll down to 'Java memory'
4. See the visual bug

**Expected behavior**
_A space between the memory, to see it better, and even select it_

**Possible solutions**
_Some ideas of how you would solve this issue, if possible_

**Screenshots**
_`flex: between`?_

**Operating System:**
- OS: Windows 11
- Launcher Version: 2.0.1
- Java Version: 17

**Additional context**
![the visual inconscistency](https://github.com/gorilla-devs/GDLauncher/assets/39814943/e3c3f899-95d5-443b-9999-8d76b846d235)

**Comment by Eskaan** [comment]
This is the issue tracker for the 1.x version of the launcher (only).

Judging by the UI this seems to be a very similar issue like we have in 1.x too btw: #1090.

**Comment by Eskaan** [comment]
If you want to report the issue to the current development team, I'd recommend posting it on discord.
I'll also relay this information to the dev team.
