### ISSUE TITLE
Adhere to MacOS Design Standards

### ISSUE THREAD

**Issue by thesamgordon** [killpowa/Twickt-Launcher#1609]
MacOS has specific guidelines for app icons outlined [here](https://developer.apple.com/design/human-interface-guidelines/app-icons). 

GDLauncher stands out, and it does not adhere to these guidelines:
<img width="1064" alt="image" src="https://github.com/gorilla-devs/GDLauncher/assets/51384418/961bc79c-a8f0-4204-aa16-adeeedd059de">

Example of an icon that does adhere to the standards:
<img width="1064" alt="image" src="https://github.com/gorilla-devs/GDLauncher/assets/51384418/d0670b93-74ff-4dba-954a-d095e82159cc">

I have attached the icon designed above, if needed, but the quality is not great, as I just took this of your website. Would be open to changing the image source if provided with a higher quality version.
This of course should be at the bottom of the priority scale. But I'm putting it here anyways.

![GDLauncher MacOS](https://github.com/gorilla-devs/GDLauncher/assets/51384418/04b5d699-18fe-4992-8083-0322aaf4829a)

**Comment by thesamgordon** [comment]
This belongs in the new Carbon GitHub! Sorry for the unnecessary report.

**Comment by Eskaan** [comment]
No problem, you're the second person mistaking the legacy version for the rewrite, even tho this probably applies to the legacy version too. Good you noticed it yourself and have a good day.
