### ISSUE TITLE
Forge not downloading/opening

### ISSUE THREAD

**Issue by nmsjayden** [killpowa/Twickt-Launcher#1611]
When I try to download Forge for 1.20.4 and press play, it'll say "downloading game files" then it'll go to "patching forge" and then go back to "downloading game files" in a infinite loop. I tried pressing repair and it didn't work. 

Also I looked in the files and installing.lock never seems to get any data.

**Operating System:**
- OS: [linux]
- Launcher Version: [v1.1.30]
- Java Version: [idrk but is installed 8/16]
- Minecraft Version: [e.g. 1.20.4]
- Mod Loader: [Forge]
Something I found in console while downloading:
![Screenshot 2024-04-12 8 57 50 PM](https://github.com/gorilla-devs/GDLauncher/assets/114900435/1356a698-275a-4393-a80f-0daf6313cd7d)

**Comment by Eskaan** [comment]
It looks like there are files missing.
Can you try to install a new instance with this version of the game (and preferably reproducing the issue there)?
