### ISSUE TITLE
Game close when loading bootstrap resources

### ISSUE THREAD

**Issue by Tataridayo** [killpowa/Twickt-Launcher#1612]
- [✅ ] I searched the issue tracker for other issues covering my case
- [ ✅] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

**Describe the bug**
hen I start Minecraft on GDLauncher, loading screen for Minecraft appear and load until bootstrap resources loading. And then game tab close and nothing appear after that.

**To Reproduce**
1. Add Instance on GDLauncher
2. Click play botton
3. Load until screen that said bootstrap resources
4. tab close.

**Expected behavior**
The launcher to start normally, load until bootstrap resources

**Possible solutions**
N/A

**Screenshots**
<img width="868" alt="Screenshot 2024-04-18 at 10 35 36 PM" src="https://github.com/gorilla-devs/GDLauncher/assets/102757136/b965feed-f1a7-49d5-bedb-f00f2f445714">
This is screenshot of loading screen loading bootstrap.

**Operating System:**
- OS: Macbook Ventura 8GB memory
- Launcher Version: 2.0.6
- Java Version: 8
- Minecraft Version: 1.20.4
- Mod Loader: Forge

**Additional context**
It works on normal Minecraft launcher so I think this is GDLauncher issue.

**Comment by Eskaan** [comment]
This is an issue for the rewrite of the launcher (v2.0 i.e. GDL Carbon).
This issue tracker is for the old version, I would recommend you report this issue on the discord server.
