### ISSUE TITLE
Arm64 version won't install

### ISSUE THREAD

**Issue by Longtimegnu7424** [killpowa/Twickt-Launcher#1615]
When trying to install using GDLauncher-linux-setup.AppImage i get this error.

Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 73 entries
Box64 with Dynarec v0.2.9 950241d5 built on Jun  9 2024 06:19:09
BOX64: Detected 48bits at least of address space
Counted 50 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/:/snap/bin/:/home/bkyef/.dotnet/tools/
Looking for /home/bkyef/Downloads/GDLauncher-linux-setup.AppImage
Rename process to "GDLauncher-linux-setup.AppImage"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libfuse.so.2
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A76 with 4 Cores
Will use Hardware counter measured at 54.0 MHz emulating 3.4 GHz
Params database has 73 entries
Box64 with Dynarec v0.2.9 950241d5 built on Jun  9 2024 06:19:09
BOX64: Detected 48bits at least of address space
Counted 55 Env var
BOX64 LIB PATH: /tmp/.mount_GDLauncdPCLb/usr/lib/:./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/tmp/.mount_GDLauncdPCLb/:/tmp/.mount_GDLauncdPCLb/usr/sbin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/games/:/usr/local/games/:/snap/bin/:/snap/bin/:/home/bkyef/.dotnet/tools/
Looking for /tmp/.mount_GDLauncdPCLb/gdlauncher
Rename process to "gdlauncher"
Redirecting overridden malloc from symtab function for /tmp/.mount_GDLauncdPCLb/gdlauncher
Using emulated /tmp/.mount_GDLauncdPCLb/libffmpeg.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libnss3.so
Using native(wrapped) libnssutil3.so
Using native(wrapped) libsmime3.so
Using native(wrapped) libnspr4.so
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libcups.so.2
Using native(wrapped) libdbus-1.so.3
Using native(wrapped) libdrm.so.2
Using native(wrapped) libgtk-3.so.0
Using native(wrapped) libgdk-3.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libcairo.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXdamage.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXrender.so.1
Using native(wrapped) libgbm.so.1
Using native(wrapped) libexpat.so.1
Using native(wrapped) libxkbcommon.so.0
Using native(wrapped) libasound.so.2
Using native(wrapped) libatspi.so.0
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Warning: Weak Symbol _ZTHN15partition_alloc8internal14g_thread_cacheE not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea0188 (0x894f546)
Warning: Weak Symbol _ZTHN2v88internal12trap_handler21g_thread_in_wasm_codeE not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea0fd8 (0x89511e6)
Warning: Weak Symbol _ZTHN3WTF16g_is_main_threadE not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea1018 (0x8951266)
Warning: Weak Symbol OPENSSL_memory_alloc not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea1420 (0x8951a76)
Warning: Weak Symbol OPENSSL_memory_free not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea1428 (0x8951a86)
Warning: Weak Symbol sdallocx not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea1430 (0x8951a96)
Warning: Weak Symbol OPENSSL_memory_get_size not found, cannot apply R_X86_64_JUMP_SLOT @0x108ea1438 (0x8951aa6)
free(): invalid pointer
NativeBT: /tmp/.mount_GDLauncdPCLb/gdlauncher() [0x34a1be4c]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffff893967e0]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x853f8) [0xffff892053f8]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(raise+0x1c) [0xffff891bb6ac]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(abort+0xf4) [0xffff891a6ec0]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x78f74) [0xffff891f8f74]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x8fb08) [0xffff8920fb08]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x91e1c) [0xffff89211e1c]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(free+0xd8) [0xffff892148c8]
NativeBT: [0xffff84d68024]
EmulatedBT: box64(free+0) [0x100a0]
EmulatedBT: /tmp/.mount_GDLauncdPCLb/gdlauncher+8764586 [0x108764586]
EmulatedBT: /tmp/.mount_GDLauncdPCLb/gdlauncher+876d5e4 [0x10876d5e4]
EmulatedBT: /tmp/.mount_GDLauncdPCLb/gdlauncher(__libc_csu_init+45) [0x10203d585]
EmulatedBT: box64(ExitEmulation+0) [0x10080]
EmulatedBT: /tmp/.mount_GDLauncdPCLb/gdlauncher(+2a) [0x101d008ea]
144538|SIGABRT @0xffff892053f8 (???(/lib/aarch64-linux-gnu/libc.so.6+0x853f8)) (x64pc=0x100a0/???:"???", rsp=0xffff88d31b68, stack=0xffff88533000:0xffff88d33000 own=(nil) fp=0xffff88d31be0), for accessing 0x3e80002349a (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000000000000 RSP-0x18:0x0000000101017ea7 RSP-0x10:0x00000001090366c0 RSP-0x08:0x0000ffff88d31be0
RSP+0x00:0x0000000108764d40 RSP+0x08:0x0000ffff88d31b78 RSP+0x10:0x0000000000000000 RSP+0x18:0x0000000000000000
RAX:0x00000460002147e0 RCX:0x0000000000007ef0 RDX:0x0000000010400058 RBX:0x00000460002147e0 
RSP:0x0000ffff88d31b68 RBP:0x0000ffff88d31be0 RSI:0x00000460002147f8 RDI:0x00000460002147e0 
 R8:0x0000000000000030  R9:0x0000000000000009 R10:0x0000000000000001 R11:0x0000000000000006 
R12:0x0000ffff88d31b79 R13:0x0000000000000000 R14:0x00000460002147e0 R15:0x00000001090366c0 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053 
Aborted (core dumped)

**Operating System:**
       ubuntu 23.10

**Comment by Eskaan** [comment]
I don't think we distribure ARM builds yet. You can try installing it from source, as there has been work to support it in principle.

Also you should note that this version of the launcher isn't actively being developed anymore.

**Comment by Longtimegnu7424** [comment]
I think I've got it working. I installed it with pi-apps on Ubuntu and now it auto setting up.
